Repository apache/drill, pull requests merged in 2020-12, with the labels that each got.

#2118 Drill-7813: Excel Reader Crashes on Formulae Which Return Strings
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
  contrib/format-excel/src/test/resources/excel/numeric-formula.xlsx
  contrib/format-excel/src/test/resources/excel/text-formula.xlsx
Labels: bug

#2119 DRILL-7771: Order by and limit transactions in RDBMS cannot be pushdown
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcRuleBase.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcSort.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMySQLIT.java
Labels: bug

#2123 DRILL-7787: Apache drill failed to start
  _docs/install/045-distributed-mode-prerequisites.md
Labels: documentation

#2122 [DRILL-7817] Allow immediate parsing of the useragent from within the HTTPD LogFormat format plugin.
  contrib/format-httpd/README.md
  contrib/format-httpd/pom.xml
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogBatchReader.java
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogFormatConfig.java
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogFormatPlugin.java
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogRecord.java
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdParser.java
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdUtils.java
  contrib/format-httpd/src/main/resources/bootstrap-format-plugins.json
  contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReader.java
  contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReaderUserAgent.java
  contrib/format-httpd/src/test/resources/httpd/multiformat.access_log
  contrib/format-httpd/src/test/resources/httpd/typeremap.log
  contrib/format-httpd/src/test/resources/logback-test.txt
  contrib/udfs/pom.xml
  exec/java-exec/pom.xml
  pom.xml
Labels: doc-impacting, enhancement

#2126 DRILL-7818 SplitPart (SPLIT_PART) UDF work correct only with one-row …
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestStringFunctions.java
Labels: bug

#2116 DRILL-7532: Convert Syslog to EVF
  contrib/format-syslog/pom.xml
  contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogBatchReader.java
  contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogFormatConfig.java
  contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogFormatPlugin.java
  contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogRecordReader.java
  contrib/format-syslog/src/main/resources/bootstrap-format-plugins.json
  contrib/format-syslog/src/test/java/org/apache/drill/exec/store/syslog/TestSyslogFormat.java
  contrib/format-syslog/src/test/resources/syslog/test.syslog1
Labels: refactoring

#2129 DRILL-7823 - Add XML Format Plugin
  contrib/format-xml/README.md
  contrib/format-xml/pom.xml
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatConfig.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatPlugin.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLMap.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLUtils.java
  contrib/format-xml/src/main/resources/bootstrap-format-plugins.json
  contrib/format-xml/src/main/resources/drill-module.conf
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/format-xml/src/test/resources/xml/attributes.xml
  contrib/format-xml/src/test/resources/xml/deep-nested.xml
  contrib/format-xml/src/test/resources/xml/deep-nested2.xml
  contrib/format-xml/src/test/resources/xml/nested.xml
  contrib/format-xml/src/test/resources/xml/really-simple-nested.xml
  contrib/format-xml/src/test/resources/xml/simple.xml
  contrib/format-xml/src/test/resources/xml/simple_schema.xsd
  contrib/format-xml/src/test/resources/xml/very-nested.xml
  contrib/native/client/src/protobuf/UserBitShared.pb.cc
  contrib/native/client/src/protobuf/UserBitShared.pb.h
  contrib/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  protocol/src/main/java/org/apache/drill/exec/proto/UserBitShared.java
  protocol/src/main/protobuf/UserBitShared.proto
Labels: doc-impacting, enhancement, new-format

#2131 DRILL-7830: Add XML as Supported Format for HTTP Plugin
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLUtils.java
  contrib/storage-http/README.md
  contrib/storage-http/pom.xml
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/resources/data/response.xml
Labels: doc-impacting, enhancement
