Repository apache/drill, pull requests merged in 2020-03, with the labels that each got.

#2013 Clean up a bit, add example for s3 storage of query profiles
  _docs/configure-drill/configuration-options/040-persistent-configuration-storage.md
Labels: documentation

#1986 Additional changes for Drill Metastore docs
  _docs/performance-tuning/005-drill-metastore.md
  _docs/performance-tuning/drill-metastore/010-using-drill-metastore.md
  _docs/performance-tuning/drill-metastore/030-drill-iceberg-metastore.md
  _docs/sql-reference/sql-commands/005-supported-sql-commands.md
  _docs/sql-reference/sql-commands/007-analyze-table-refresh-metadata.md
Labels: documentation

#2033 DRILL-7652: Add time_bucket() function for time series analysis
  contrib/udfs/README.md
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/TimeBucketFunctions.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestTimeBucketFunction.java
Labels: documentation, enhancement

#2030 Update docs for Metastore to point that all format plugins are supported
  _docs/connect-a-data-source/035-plugin-configuration-basics.md
  _docs/connect-a-data-source/plugins/080-rdbms-storage-plugin.md
  _docs/connect-a-data-source/plugins/114-image-metadata-format-plugin.md
  _docs/performance-tuning/drill-metastore/010-using-drill-metastore.md
  _docs/query-data/query-a-file-system/005-querying-a-file-system-introduction.md
  _docs/query-data/query-a-file-system/009-querying-avro-files.md
  _docs/sql-reference/sql-commands/007-analyze-table-refresh-metadata.md
  _docs/sql-reference/sql-commands/021-create-schema.md
  images/7671b34d6e8a4d050f75278f10f1a08.jpg
Labels: documentation

#2018 DRILL-7633: Fixes for union and repeated list accessors
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/impl/TestResultSetLoaderUnions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/rowSet/TestSchemaBuilder.java
  exec/java-exec/src/test/java/org/apache/drill/test/rowSet/RowSetComparison.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/VariantColumnMetadata.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/VariantSchema.java
  exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/VariantWriter.java
  exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/writer/UnionVectorShim.java
Labels: code cleanup, refactoring

#2039 DRILL-7663: Code refactor to DefaultFunctionResolver
  exec/java-exec/src/main/java/org/apache/drill/exec/resolver/DefaultFunctionResolver.java
Labels: code cleanup, refactoring
