Repository apache/drill, pull requests merged in 2020-02, with the labels that each got.

#1973 DRILL-7575: Fix typo in class name of FormSecurityHandler
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/FormSecurityHandler.java
Labels: Code-cleanup

#1982 DRILL-7584: Fix method name spelling
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePluginConfig.java
Labels: Code-cleanup

#1998 Some little fixups for the docs for date & time functions
  _docs/sql-reference/sql-functions/030-date-time-functions-and-arithmetic.md
Labels: documentation

#1992 DRILL-7596: drill-format-esri module Uses Hard Coded Version Number
  contrib/format-esri/pom.xml
Labels: code cleanup

#1980 DRILL-7561: Document REST API authentication
  _docs/developer-information/rest-api/010-rest-api-introduction.md
Labels: documentation

#1979 DRILL-7580: Fix Web UI link
  _docs/developer-information/rest-api/010-rest-api-introduction.md
Labels: documentation
