Repository apache/drill, pull requests merged in 2021-12, with the labels that each got.

#2391 DRILL-8051: Update the JQuery for Vulnerability issue
  drill-yarn/src/main/resources/drill-am/generic.ftl
Labels: Updates, Security, UI

#2392 DRILL-8064: Cannot query text files with names that contain a backslash
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSelection.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestGlob.java
Labels: bug

#2393 DRILL-8066: Convert non-finite floating point literals to string RexLiterals
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillConstExecutor.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestMathFunctionsWithNanInf.java
Labels: bug

#2397 DRILL-8072: Fix NPE in HTTP Post Requests
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
Labels: bug

#2396 DRILL-8069: remove use of excel sheet getLastRowNum
  contrib/format-excel/pom.xml
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
Labels: bug

#2353 DRILL-7983: Add a REST API to support the get running or completed profiles
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestQueryProfiles.java
Labels: enhancement, Updates, doc-impacting

#2394 DRILL-8047: Add a custom authn provider for HashiCorp Vault
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/security/VaultUserAuthenticator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/DrillRestLoginService.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/vault/VaultCredentialsProvider.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestHtpasswdFileUserAuthenticator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestVaultUserAuthenticator.java
Labels: doc-impacting, Security

#2403 DRILL-8074: Upgrade log4j because of CVE-2021-44228
  contrib/format-excel/pom.xml
Labels: Security

#2387 DRILL-8055: Druid Plugin support for V0.20 and up
  contrib/storage-druid/README.md
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/DruidCompareFunctionProcessor.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/DruidGroupScan.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/DruidRecordReader.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/DruidStoragePlugin.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/druid/DruidScanResponse.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/druid/DruidSelectResponse.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/druid/PagingSpec.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/druid/ScanQuery.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/druid/ScanQueryBuilder.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/rest/DruidQueryClient.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/DruidTestConstants.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/TestDataGenerator.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/TestDruidQueries.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/rest/DruidQueryClientTest.java
  contrib/storage-druid/src/test/resources/druid/docker-compose.yaml
  contrib/storage-druid/src/test/resources/druid/environment.env
  contrib/storage-druid/src/test/resources/wikipedia-index.json
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestDrillSpnegoAuthenticator.java
Labels: enhancement, code cleanup, Updates

#2398 DRILL-8073: Add support for persistent table and storage aliases
  contrib/format-iceberg/src/test/java/org/apache/drill/exec/store/iceberg/IcebergQueriesTest.java
  docs/dev/Aliases.md
  exec/java-exec/src/main/codegen/data/Parser.tdd
  exec/java-exec/src/main/codegen/includes/parserImpls.ftl
  exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicRootSchema.java
  exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicSchema.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/AliasRegistry.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/AliasRegistryProvider.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/AliasTarget.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/Aliases.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/EmptyAliases.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/NoopAliasRegistry.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/PersistentAliasRegistry.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/PersistentAliasesTable.java
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/ResolvedAliases.java
  exec/java-exec/src/main/java/org/apache/drill/exec/coord/zk/PathUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/conversion/DrillValidator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/BaseAliasHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/CreateAliasHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DrillTableInfo.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DropAliasHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DropAllAliasesHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/SqlCreateAlias.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/SqlDropAlias.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/SqlDropAllAliases.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/DrillbitContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/SchemaTreeProvider.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/AliasesIterator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/ExtendedOptionIterator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/SystemTable.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/test/java/org/apache/drill/PlanningBase.java
  exec/java-exec/src/test/java/org/apache/drill/alias/TestAliasCommands.java
  exec/java-exec/src/test/java/org/apache/drill/alias/TestAliasSubstitution.java
  exec/java-exec/src/test/java/org/apache/drill/alias/TestAliasSystemTables.java
  exec/java-exec/src/test/java/org/apache/drill/exec/work/metadata/TestMetadataProvider.java
  exec/java-exec/src/test/java/org/apache/drill/test/OperatorFixture.java
Labels: enhancement, documentation

#2404 DRILL-8076: Remove unneeded Vault token BOOT opt
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/security/VaultUserAuthenticator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestVaultUserAuthenticator.java
Labels: Minor Update, Security

#2405 DRILL-8074: Second upgrade of log4j (2.16 now) because of CVE-2021-44228
  contrib/format-excel/pom.xml
Labels: Security

#2384 DRILL-8015: Add MongoDB Metastore implementation
  contrib/storage-mongo/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  distribution/src/main/resources/drill-metastore-override-example.conf
  exec/java-exec/src/main/java/org/apache/drill/exec/record/SchemaUtil.java
  metastore/metastore-api/src/test/java/org/apache/drill/metastore/TestData.java
  metastore/metastore-api/src/test/java/org/apache/drill/metastore/components/tables/AbstractBasicTablesRequestsTest.java
  metastore/mongo-metastore/pom.xml
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/MongoMetastore.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/MongoMetastoreContext.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/components/tables/MongoTables.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/components/tables/TablesOperationTransformer.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/components/tables/TablesOutputDataTransformer.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/components/tables/TablesTransformer.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/config/MongoConfigConstants.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/exception/MongoMetastoreException.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/operate/MongoDelete.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/operate/MongoMetadata.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/operate/MongoModify.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/operate/MongoOperation.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/operate/MongoRead.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/operate/Overwrite.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/transform/FilterExpressionVisitor.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/transform/FilterTransformer.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/transform/InputDataTransformer.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/transform/OperationTransformer.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/transform/OutputDataTransformer.java
  metastore/mongo-metastore/src/main/java/org/apache/drill/metastore/mongo/transform/Transformer.java
  metastore/mongo-metastore/src/main/resources/drill-metastore-module.conf
  metastore/mongo-metastore/src/test/java/org/apache/drill/metastore/mongo/MongoBaseTest.java
  metastore/mongo-metastore/src/test/java/org/apache/drill/metastore/mongo/components/tables/TestMongoBasicTablesRequests.java
  metastore/mongo-metastore/src/test/java/org/apache/drill/metastore/mongo/components/tables/TestTablesInputDataTransformer.java
  metastore/mongo-metastore/src/test/java/org/apache/drill/metastore/mongo/components/tables/TestTablesOperationTransformer.java
  metastore/mongo-metastore/src/test/java/org/apache/drill/metastore/mongo/components/tables/TestTablesOutputDataTransformer.java
  metastore/pom.xml
  pom.xml
Labels: enhancement, documentation

#2407 DRILL-8078: Add WEEK to Date Extract
  exec/java-exec/src/main/codegen/data/ExtractTypes.tdd
  exec/java-exec/src/main/codegen/templates/DateIntervalFunctionTemplates/Extract.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillOptiq.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/TypeInferenceUtils.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestNewDateFunctions.java
  exec/vector/src/main/java/org/apache/drill/exec/vector/DateUtilities.java
Labels: enhancement, doc-impacting, Minor Update

#2410 DRILL-8080: Enable the describe Case-Insensitive for Phoenix
  contrib/storage-phoenix/pom.xml
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixSchemaFactory.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixCommandTest.java
Labels: enhancement

#2411 DRILL-8081: Maven Connection timed out
  .github/workflows/ci.yml
Labels: CI
