Repository apache/drill, pull requests merged in 2021-01, with the labels that each got.

#2127 DRILL-7552: Add Helpful Error Message on Storage Plugin Creation/Update
  exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java
Labels: enhancement

#2133 DRILL-7834: Add Utility Functions for Compressed Files
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/DrillFileSystem.java
Labels: code cleanup

#2134 DRILL-7835: XML Reader Not Reading XML Nested Attributes Correctly
  contrib/format-xml/README.md
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/format-xml/src/test/resources/xml/nested-with-attributes.xml
  contrib/format-xml/src/test/resources/xml/very-nested.xml
Labels: bug

#2136 DRILL-7836: Format Plugins Hang with Compressed Files
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/DrillFileSystem.java
Labels: bug

#2132 DRILL-7831: Drill Fails To Read XML File with Self Closing Tags
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLUtils.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLUtils.java
  contrib/format-xml/src/test/resources/xml/very-nested-with-attributes.xml
  contrib/format-xml/src/test/resources/xml/weather.xml
Labels: bug

#2140 DRILL-7840: Add OWASP Dependency Report to Pom.XML
  docs/dev/Environment.md
  pom.xml
Labels: code cleanup, doc-impacting, enhancement

#2086 Typo Rectified
  _docs/query-data/060-querying-the-information-schema.md
Labels: documentation

#2144 POI 5.0.0 release
  contrib/format-excel/pom.xml
Labels: Minor Update

#2141 DRILL-7536: Convert Image format to EVF
  contrib/format-image/README.md
  contrib/format-image/pom.xml
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/GenericMetadataDescriptor.java
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/GenericMetadataDirectory.java
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/GenericMetadataReader.java
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/ImageBatchReader.java
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/ImageDirectoryProcessor.java
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/ImageFormatConfig.java
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/ImageFormatPlugin.java
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/ImageMetadataUtils.java
  contrib/format-image/src/main/resources/bootstrap-format-plugins.json
  contrib/format-image/src/main/resources/drill-module.conf
  contrib/format-image/src/test/java/org/apache/drill/exec/store/image/TestImageRecordReader.java
  contrib/format-image/src/test/java/org/apache/drill/exec/store/image/TestImageTagValue.java
  contrib/format-image/src/test/resources/image/1_webp_a.webp
  contrib/format-image/src/test/resources/image/LearningApacheDrill.jpg
  contrib/format-image/src/test/resources/image/adobeJpeg1.eps
  contrib/format-image/src/test/resources/image/avi.json
  contrib/format-image/src/test/resources/image/bmp.json
  contrib/format-image/src/test/resources/image/eps.json
  contrib/format-image/src/test/resources/image/gif.json
  contrib/format-image/src/test/resources/image/ico.json
  contrib/format-image/src/test/resources/image/jpeg.json
  contrib/format-image/src/test/resources/image/mov.json
  contrib/format-image/src/test/resources/image/mp4.json
  contrib/format-image/src/test/resources/image/pcx.json
  contrib/format-image/src/test/resources/image/png.json
  contrib/format-image/src/test/resources/image/psd.json
  contrib/format-image/src/test/resources/image/rose-128x174-24bit-lzw.tiff
  contrib/format-image/src/test/resources/image/rose-128x174-24bit.bmp
  contrib/format-image/src/test/resources/image/rose-128x174-24bit.pcx
  contrib/format-image/src/test/resources/image/rose-128x174-32bit-alpha.png
  contrib/format-image/src/test/resources/image/rose-128x174-32bit-alpha.psd
  contrib/format-image/src/test/resources/image/rose-128x174-8bit-alpha.gif
  contrib/format-image/src/test/resources/image/rose-32x32-32bit-alpha.ico
  contrib/format-image/src/test/resources/image/sample.avi
  contrib/format-image/src/test/resources/image/sample.mov
  contrib/format-image/src/test/resources/image/sample.mp4
  contrib/format-image/src/test/resources/image/sample.wav
  contrib/format-image/src/test/resources/image/tiff.json
  contrib/format-image/src/test/resources/image/wav.json
  contrib/format-image/src/test/resources/image/webp.json
  contrib/format-image/src/test/resources/image/withExifAndIptc.jpg
  contrib/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/store/image/ImageFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/image/ImageRecordReader.java
  exec/java-exec/src/main/resources/bootstrap-storage-plugins.json
  exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestFormatPluginOptionExtractor.java
  exec/java-exec/src/test/resources/plugins/mock-plugin-upgrade.json
  exec/jdbc-all/pom.xml
  exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/writer/AbstractScalarWriter.java
Labels: code cleanup

#2145 Fix formatting on "MongoDB Storage Plugin" page
  _docs/connect-a-data-source/plugins/090-mongodb-storage-plugin.md
Labels: documentation

#2148 Fix formatting on "Configuring Storage Plugins" page
  _docs/connect-a-data-source/036-configuring-storage-plugins.md
Labels: documentation

#2146 DRILL-7842:Fix BaseTestInheritance test case
  exec/java-exec/src/test/java/org/apache/drill/TestforBaseTestInheritance.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestStackAnalyzer.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/schema/TestDynamicSchemaFilter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/schema/TestProjectedPath.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/schema/TestSchemaTrackerDefined.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/impl/TestProjectionFilter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/project/TestProjectedPath.java
Labels: bug, code cleanup

#2147 [DRILL-7847] Give all maven modules a consistent name
  common/pom.xml
  contrib/data/pom.xml
  contrib/data/tpch-sample-data/pom.xml
  contrib/format-esri/pom.xml
  contrib/format-excel/pom.xml
  contrib/format-hdf5/pom.xml
  contrib/format-httpd/pom.xml
  contrib/format-image/pom.xml
  contrib/format-ltsv/pom.xml
  contrib/format-maprdb/pom.xml
  contrib/format-spss/pom.xml
  contrib/format-syslog/pom.xml
  contrib/format-xml/pom.xml
  contrib/pom.xml
  contrib/storage-druid/pom.xml
  contrib/storage-elasticsearch/pom.xml
  contrib/storage-hbase/pom.xml
  contrib/storage-hive/core/pom.xml
  contrib/storage-hive/hive-exec-shade/pom.xml
  contrib/storage-hive/pom.xml
  contrib/storage-http/pom.xml
  contrib/storage-jdbc/pom.xml
  contrib/storage-kafka/pom.xml
  contrib/storage-kudu/pom.xml
  contrib/storage-mongo/pom.xml
  contrib/storage-opentsdb/pom.xml
  contrib/udfs/pom.xml
  distribution/pom.xml
  docs/dev/DevDocs.md
  docs/dev/Maven.md
  drill-shaded/pom.xml
  drill-yarn/pom.xml
  exec/java-exec/pom.xml
  exec/jdbc-all/pom.xml
  exec/jdbc/pom.xml
  exec/memory/base/pom.xml
  exec/memory/pom.xml
  exec/pom.xml
  exec/rpc/pom.xml
  exec/vector/pom.xml
  logical/pom.xml
  metastore/iceberg-metastore/pom.xml
  metastore/metastore-api/pom.xml
  metastore/pom.xml
  metastore/rdbms-metastore/pom.xml
  pom.xml
  protocol/pom.xml
  tools/fmpp/pom.xml
  tools/pom.xml
Labels: code cleanup

#2154 DRILL-7849: Display error message when cannot enable storage plugin
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/java-exec/src/main/resources/rest/alertModals.ftl
  exec/java-exec/src/main/resources/rest/confirmationModals.ftl
  exec/java-exec/src/main/resources/rest/static/js/serverMessage.js
  exec/java-exec/src/main/resources/rest/storage/list.ftl
  exec/java-exec/src/main/resources/rest/storage/update.ftl
Labels: enhancement

#2152 DRILL-92: Cassandra storage plugin implementation based on Calcite adapter
  contrib/pom.xml
  contrib/storage-cassandra/README.md
  contrib/storage-cassandra/pom.xml
  contrib/storage-cassandra/src/main/java/com/codahale/metrics/JmxReporter.java
  contrib/storage-cassandra/src/main/java/org/apache/calcite/adapter/cassandra/CalciteUtils.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraStorageConfig.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraStoragePlugin.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/plan/CassandraEnumerablePrelContext.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/plan/DrillCassandraLimitRule.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/schema/CassandraDrillSchema.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/schema/CassandraDynamicTable.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/schema/CassandraRootDrillSchema.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/schema/CassandraRootDrillSchemaFactory.java
  contrib/storage-cassandra/src/main/resources/bootstrap-storage-plugins.json
  contrib/storage-cassandra/src/main/resources/drill-module.conf
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/BaseCassandraTest.java
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/CassandraComplexTypesTest.java
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/CassandraPlanTest.java
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/CassandraQueryTest.java
  contrib/storage-cassandra/src/test/resources/queries.cql
  distribution/pom.xml
  distribution/src/assemble/component.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/record/ColumnConverter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/EnumerablePrelContext.java
  pom.xml
Labels: doc-impacting, new-storage

#2150 DRILL-7827: Move the Pcapng format plugin to contrib folder
  contrib/format-pcapng/README.md
  contrib/format-pcapng/pom.xml
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PacketDecoder.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PcapColumn.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PcapngBatchReader.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PcapngFormatConfig.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PcapngFormatPlugin.java
  contrib/format-pcapng/src/main/resources/bootstrap-format-plugins.json
  contrib/format-pcapng/src/main/resources/drill-module.conf
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcapng/TestPcapngRecordReader.java
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcapng/TestPcapngStatRecordReader.java
  contrib/format-pcapng/src/test/resources/pcapng/example.pcapng
  contrib/format-pcapng/src/test/resources/pcapng/sniff.pcapng
  contrib/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/store/pcapng/package-info.java
  exec/java-exec/src/main/resources/bootstrap-storage-plugins.json
  exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestFormatPluginOptionExtractor.java
  exec/java-exec/src/test/resources/plugins/mock-plugin-upgrade.json
  exec/jdbc-all/pom.xml
Labels: code cleanup

#2151 [Minor Fix] Incorrect Tag Name for Image
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/GenericMetadataDirectory.java
  contrib/format-image/src/test/java/org/apache/drill/exec/store/image/TestImageRecordReader.java
  contrib/format-image/src/test/resources/image/avi.json
  contrib/format-image/src/test/resources/image/bmp.json
  contrib/format-image/src/test/resources/image/eps.json
  contrib/format-image/src/test/resources/image/gif.json
  contrib/format-image/src/test/resources/image/ico.json
  contrib/format-image/src/test/resources/image/jpeg.json
  contrib/format-image/src/test/resources/image/mov.json
  contrib/format-image/src/test/resources/image/mp4.json
  contrib/format-image/src/test/resources/image/pcx.json
  contrib/format-image/src/test/resources/image/png.json
  contrib/format-image/src/test/resources/image/psd.json
  contrib/format-image/src/test/resources/image/tiff.json
  contrib/format-image/src/test/resources/image/wav.json
  contrib/format-image/src/test/resources/image/webp.json
Labels: bug
