Repository apache/drill, pull requests merged in 2021-07, with the labels that each got.

#2266 [DOC UPDATE] Index.html Chinese Translation
  zh/index.html
Labels: documentation

#2259 DRILL-7931: Rowtype mismatch in DrillReduceAggregatesRule
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillReduceAggregatesRule.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java
Labels: bug

#2267 DRILL-7968: ANALYZE TABLE ... REFRESH METADATA fails with FLOAT4 column.
  exec/java-exec/src/main/java/org/apache/drill/exec/store/pojo/PojoWriters.java
  exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestMetastoreCommands.java
Labels: bug

#2244 DRILL-7941 Update JUnit from 4.13.2 to 5.7.2
  common/pom.xml
  common/src/test/java/org/apache/drill/common/util/RepeatTestRule.java
  common/src/test/java/org/apache/drill/test/Drill2130CommonHamcrestConfigurationTest.java
  exec/jdbc-all/pom.xml
  logical/pom.xml
  logical/src/test/java/org/apache/drill/common/expression/PathSegmentTests.java
  logical/src/test/java/org/apache/drill/common/expression/SchemaPathTest.java
  logical/src/test/java/org/apache/drill/common/expression/parser/TreeTest.java
  pom.xml
Labels: Updates, doc-impacting

#2271 [MINOR UPDATE] Update Patch Review Script to use Python 3
  .gitignore
  tools/drill-patch-review.py
Labels: Minor Update

#2273 DRILL-7971: Support Elasticsearch authentication
  pom.xml
Labels: bug

#2276 Update 025-tutorial-develop-a-simple-function.md
  _docs/en/develop-custom-functions/025-tutorial-develop-a-simple-function.md
Labels: documentation

#2225 DRILL-7922: Add feature of viewing external profile in web UI
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
  exec/java-exec/src/main/resources/rest/profile/list.ftl
Labels: UI, enhancement

#2275 DRILL-7972: ClassCastException when joining RDBMS and Elasticsearch tables
  contrib/storage-cassandra/src/main/java/org/apache/calcite/adapter/cassandra/CalciteUtils.java
  contrib/storage-elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/CalciteUtils.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcIntermediatePrelConverterRule.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithH2IT.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/EnumerableIntermediatePrelConverterRule.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/EnumPluginTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/plan/EnumMockPlugin.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/plan/EnumMockRel.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/plan/EnumMockSchema.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/enumerable/plan/EnumMockTable.java
  exec/java-exec/src/test/resources/drill-module.conf
Labels: bug

#2279 DRILL-7976: Fix XSS Vulnerability
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
  exec/jdbc-all/pom.xml
Labels: Security

#2280 [DOCUMENTATION] Update 024-aynchronous-parquet-reader.md
  _docs/en/performance-tuning/024-aynchronous-parquet-reader.md
Labels: documentation

#2278 DRILL-7975: Connection to Splunk Drill Storage Plugin fails intermittently
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/DruidStoragePluginConfig.java
  contrib/storage-kudu/src/test/java/org/apache/drill/store/kudu/TestKuduConnect.java
  contrib/storage-splunk/README.md
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkConnection.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
  contrib/storage-splunk/src/main/resources/bootstrap-storage-plugins.json
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkConnectionTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkPluginTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ShowTablesHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaConfig.java
  logical/src/main/java/org/apache/drill/common/logical/AbstractSecuredStoragePluginConfig.java
  pom.xml
Labels: bug, doc-impacting
