Repository apache/drill, pull requests merged in 2021-08, with the labels that each got.

#2281 [MINOR UPDATE]: Add an .editorconfig file providing style hints to editors and IDEs
  .editorconfig
Labels: Minor Update

#2283 DRILL-7979: Self-Closing XML Tags Cause Schema Change Exceptions
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLUtils.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLUtils.java
  contrib/format-xml/src/test/resources/xml/schemaChange.xml
Labels: bug

#2285 DRILL-7981: Bump commons-compress from 1.20 to 1.21 for CVE-2021-36090
  exec/jdbc-all/pom.xml
  pom.xml
Labels: Security

#2287 DRILL-7982: Timed out waiting for container port to open
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/TestCassandraSuit.java
Labels: Minor Update

#2286 [DOC UPDATE] Translate Tutorial to Chinese 7/14
  _docs/zh/tutorials/050-analyzing-highly-dynamic-datasets.md
  _docs/zh/tutorials/060-analyzing-social-media.md
Labels: documentation

#2284 DRILL-7926: Age Function Fix
  exec/java-exec/src/main/codegen/templates/DateIntervalFunctionTemplates/AgeFunction.java
  exec/java-exec/src/main/codegen/templates/DateIntervalFunctionTemplates/TimestampDiffFunction.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/DateTypeFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/ContextInformation.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestDateFunctions.java
  exec/java-exec/src/test/resources/functions/date/age.json
Labels: bug

#2297 DRILL-7988: Add credentials provider support for API connections in HTTP plugin
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  lombok.config
  pom.xml
Labels: enhancement, doc-impacting
