Repository apache/drill, pull requests merged in 2021-05, with the labels that each got.

#2208 DRILL-7893: Column alias is not working for a parquet file
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/ComplexToJsonPrelVisitor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/ExcessiveExchangeIdentifier.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/FinalColumnReorderer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/InsertLocalExchangeVisitor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/LateralUnnestRowIDVisitor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/RewriteProjectToFlatten.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/RuntimeFilterVisitor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/SelectionVectorPrelVisitor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/SplitUpComplexExpressions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DefaultSqlHandler.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetFilterPushDown.java
Labels: bug

#2211 DRILL-7912: Add Sheet Names to Excel Reader
  contrib/format-excel/README.md
  contrib/format-excel/pom.xml
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
Labels: Minor Update, doc-impacting, enhancement

#2216 DRILL-7918: Dependency Updates for CVE
  contrib/storage-kudu/pom.xml
  contrib/storage-kudu/src/main/java/org/apache/drill/exec/store/kudu/KuduRecordReader.java
  pom.xml
Labels: Security, dependencies

#2212 [Minor Update] Add reset button and reduce the dialog text
  exec/java-exec/src/main/resources/rest/query/query.ftl
  exec/java-exec/src/main/resources/rest/runningQuery.ftl
  exec/java-exec/src/main/resources/rest/static/js/querySubmission.js
Labels: UI

#2213 DRILL-7913: Improve the tips using the Tooltips
  exec/java-exec/src/main/resources/rest/generic.ftl
  exec/java-exec/src/main/resources/rest/index.ftl
  exec/java-exec/src/main/resources/rest/profile/profile.ftl
  exec/java-exec/src/main/resources/rest/query/query.ftl
  exec/java-exec/src/main/resources/rest/static/css/bootstrap.min.css
  exec/java-exec/src/main/resources/rest/static/css/bootstrap.min.css.map
  exec/java-exec/src/main/resources/rest/static/js/bootstrap.min.js
  exec/java-exec/src/main/resources/rest/static/js/bootstrap.min.js.map
  exec/java-exec/src/main/resources/rest/static/js/jquery-3.4.1.min.js
  exec/java-exec/src/main/resources/rest/static/js/jquery-3.6.0.min.js
  exec/java-exec/src/main/resources/rest/static/js/popper.min.js
Labels: Minor Update, UI

#2219 DRILL-7911 Increase the max direct memory
  pom.xml
Labels: ARM-Based

#2218 DRILL-7911 Disable maven-surefire-plugin for Splunk for ARM Build
  contrib/storage-splunk/pom.xml
Labels: ARM-Based

#2222 [DOCUMENTATION] Use HTTPS for all external links in Contribution Guidelines page
  _docs/developer-information/contribute-to-drill/010-apache-drill-contribution-guidelines.md
Labels: documentation

#2223 DRILL-7923 Add a paragraph to Contribution Guidelines page about CI
  _docs/developer-information/contribute-to-drill/010-apache-drill-contribution-guidelines.md
Labels: documentation

#2224 DRILL-7920: Update Documentation for REST API
  _docs/developer-information/rest-api/010-rest-api-introduction.md
Labels: documentation

#2221 DRILL-7925 Use .asf.yaml for the website
  .asf.yaml
  _config.yml
Labels: ARM-Based

#2226 Create .asf.yaml
  .asf.yaml
  pom.xml
Labels: Minor Update

#2228 DRILL-7929: Update Kafka unit tests to use ClusterTest
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaFilterPushdownTest.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaTestBase.java
  exec/java-exec/src/test/java/org/apache/drill/test/QueryBuilder.java
Labels: code cleanup, refactoring

#2220 DRILL-7923 Use TravisCI for building and testing on Linux ARM64
  .travis.yml
  pom.xml
Labels: ARM-Based

#2217 DRILL-7911 Use TestContainers-MySQL instead of wix-embedded-mysql
  contrib/storage-cassandra/pom.xml
  contrib/storage-jdbc/pom.xml
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMySQLIT.java
  contrib/storage-jdbc/src/test/resources/mysql_config_override/mysql_override.cnf
  contrib/storage-mongo/pom.xml
  contrib/storage-splunk/pom.xml
  exec/java-exec/pom.xml
  pom.xml
Labels: ARM-Based, Minor Update, code cleanup

#2200 DRILL-7901: Bump junit from 4.12 to 4.13.2
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaFilterPushdownTest.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaTestBase.java
  pom.xml
Labels: Security, code cleanup

#2183 DRILL-6547: IllegalStateException: Tried to remove unmanaged buffer in concat function
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ComplexSchemaFunctions.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ComplexSchemaUtils.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/UserAgentFunctions.java
  exec/java-exec/src/main/codegen/templates/CastIntervalVarChar.java
  exec/java-exec/src/main/codegen/templates/Decimal/CastDecimalVarDecimal.java
  exec/java-exec/src/main/codegen/templates/Decimal/CastDecimalVarchar.java
  exec/java-exec/src/main/codegen/templates/Decimal/CastFloatDecimal.java
  exec/java-exec/src/main/codegen/templates/Decimal/CastIntDecimal.java
  exec/java-exec/src/main/codegen/templates/Decimal/CastVarCharDecimal.java
  exec/java-exec/src/main/codegen/templates/Decimal/DecimalAggrTypeFunctions1.java
  exec/java-exec/src/main/codegen/templates/Decimal/DecimalAggrTypeFunctions2.java
  exec/java-exec/src/main/codegen/templates/Decimal/DecimalAggrTypeFunctions3.java
  exec/java-exec/src/main/codegen/templates/Decimal/DecimalFunctions.java
  exec/java-exec/src/main/codegen/templates/NewValueFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/ParseQueryFunction.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/ParseUrlFunction.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StatisticsAggrFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/TDigestFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/TestBugFixes.java
Labels: bug

#2237 DRILL-7933: Update OkHTTP to Version 4.9.1
  contrib/storage-http/pom.xml
Labels: Minor Update

#2202 DRILL-7904: Update to 30-jre Guava version
  docs/dev/UpgradeGuava.md
  exec/jdbc-all/pom.xml
  pom.xml
Labels: Security, Updates, dependencies

#2236 DRILL-7135: Update to Jetty 9.4
  drill-yarn/src/main/java/org/apache/drill/yarn/appMaster/http/WebServer.java
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/DrillUserPrincipal.java
  pom.xml
Labels: Minor Update, Security

#2232 DRILL-7919: Fix reading parquet with decimal dictionary encoding
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ColumnReaderFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableFixedByteAlignedReaders.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetLogicalTypes.java
  exec/java-exec/src/test/resources/parquet/dict_dec.parquet
Labels: bug

#2238 DRILL-7934: Fix NullPointerException error when reading parquet files
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetGroupScanStatistics.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetScan.java
  exec/java-exec/src/test/resources/parquet/test_type_null.parquet
Labels: bug
