Repository apache/drill, pull requests merged in 2021-11, with the labels that each got.

#2354 DRILL-8022: Add Provided Schema Support for Excel Reader
  contrib/format-excel/pom.xml
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
  contrib/format-excel/src/test/resources/excel/schema_provisioning.xlsx
  exec/java-exec/src/test/java/org/apache/drill/test/QueryTestUtil.java
Labels: enhancement, doc-impacting, reference

#2358 Exclude .js Files From LGTM
  .lgtm.yml
  pom.xml
Labels: code cleanup, Minor Update

#2348 DRILL-8020: Add JSON Configuration Options to HTTP Rest Plugin
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpJsonOptions.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/resources/data/response2.json
Labels: enhancement, doc-impacting

#2362 DRILL-8032: Remove obsolete Python scripts from the project
  tools/drill-patch-review.py
Labels: code cleanup, refactoring

#2363 DRILL-8033: uptake POI 5.1.0
  contrib/format-excel/pom.xml
Labels: Updates

#2366 DRILL-8040: Add HTTP status codes for API errors
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/ProfileResources.java
  exec/java-exec/src/main/resources/rest/static/js/serverMessage.js
  exec/java-exec/src/main/resources/rest/storage/list.ftl
  exec/java-exec/src/main/resources/rest/storage/update.ftl
Labels: doc-impacting, Minor Update

#2365 DRILL-8039: More LGTM Code Cleanup
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5BatchReader.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5ByteDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5DoubleDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5FloatDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5IntDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5LongDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5SmallIntDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5TimestampDataWriter.java
  contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBGroupScan.java
  contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/json/JsonTableGroupScan.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseUtils.java
  contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/AvroMessageReader.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/CryptoFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/client/DrillClient.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/CollectListMapsAggFunction.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/DateTypeFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/SchemaFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/JoinUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/validate/BatchValidator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/fragment/contrib/SplittingParallelizer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/index/rules/DbScanSortRemovalRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/BitRpcUtility.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/control/Controller.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/control/WorkEventBus.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/UserServer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroBatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JsonStatisticsRecordWriter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/log/LogBatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/store/ZookeeperPersistentStore.java
  exec/java-exec/src/main/java/org/apache/drill/exec/work/batch/ControlMessageHandler.java
  exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillCursor.java
  exec/memory/base/src/main/java/org/apache/drill/exec/memory/AllocatorClosedException.java
  exec/rpc/src/main/java/org/apache/drill/exec/rpc/BasicClient.java
  exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcBus.java
  exec/rpc/src/main/java/org/apache/drill/exec/rpc/SaslEncryptionHandler.java
Labels: code cleanup, Minor Update

#2369 DRILL-8042: Select star from MongoDB with aggregated pipeline fails with empty $project error
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/RexToMongoTranslator.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoLimitPushDown.java
Labels: bug

#2357 DRILL-8027: Format plugin for Apache Iceberg
  contrib/format-iceberg/README.md
  contrib/format-iceberg/pom.xml
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergBlockMapBuilder.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergCompleteWork.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergGroupScan.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergSubScan.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergWork.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatLocationTransformer.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatMatcher.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatPlugin.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatPluginConfig.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergMetadataFileSelection.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/plan/DrillExprToIcebergTranslator.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/plan/IcebergPluginImplementor.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/read/IcebergColumnConverterFactory.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/read/IcebergRecordReader.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/read/IcebergScanBatchCreator.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/read/MapColumnConverter.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/Snapshot.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotAfter.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotById.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotByTime.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotFactory.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotsBetween.java
  contrib/format-iceberg/src/main/java/org/apache/iceberg/data/ScanTaskTableScanIterable.java
  contrib/format-iceberg/src/main/resources/bootstrap-format-plugins.json
  contrib/format-iceberg/src/main/resources/drill-module.conf
  contrib/format-iceberg/src/test/java/org/apache/drill/exec/store/iceberg/IcebergQueriesTest.java
  contrib/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractBase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/index/ExprToRex.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillProjectRel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushProjectIntoScanRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DynamicDrillTable.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/types/RelDataTypeHolder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/record/ColumnConverterFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/SubsetRemover.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FormatLocationTransformer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FormatMatcher.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/WorkspaceSchemaFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableRecordReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/AbstractPluginImplementor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/PluginImplementor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rel/StoragePluginTableScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginConverterRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginLimitRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginProjectRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/work/fragment/FragmentExecutor.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/MetadataUtils.java
  metastore/iceberg-metastore/pom.xml
  pom.xml
Labels: enhancement, documentation, new-format, reference

#2368 DRILL-8041: Fix mongo scan spec deserialization
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/BaseMongoSubScanSpec.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoScanSpec.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoSubScan.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/MongoPluginImplementor.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoQueries.java
Labels: bug

#2371 DRILL-8025: Bump HBase client version to 2.4.8
  pom.xml
Labels: Minor Update

#2370 DRILL-8007: Fix reading time / timestamp micros and binary types
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetReaderUtility.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ColumnReaderFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableFixedByteAlignedReaders.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetFixedWidthDictionaryReaders.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetToDrillTypeConverter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet2/DrillParquetGroupConverter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetLogicalTypes.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet2/TestDrillParquetReader.java
  exec/java-exec/src/test/resources/parquet2/allTypes.parquet
Labels: bug

#2372 DRILL-8043: Excel Reader Regression Fix
  contrib/format-excel/pom.xml
Labels: bug, dependencies

#2376 DRILL-8045: Fix storage export regression introduced by DRILL-8040
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/java-exec/src/main/resources/rest/static/js/serverMessage.js
Labels: bug

#2375 DRILL-8044: Update contrib/storage-hive copy of log4j Strings.java
  contrib/format-excel/pom.xml
  contrib/storage-hive/core/src/main/java/org/apache/logging/log4j/util/Strings.java
Labels: bug, code cleanup, dependencies

#2382 DRILL-8049: Make rule names for Iceberg plugin instances unique
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatPlugin.java
  contrib/format-iceberg/src/test/java/org/apache/drill/exec/store/iceberg/IcebergQueriesTest.java
Labels: bug

#2383 DRILL-8050: Fix license-maven-plugin unknown file extension warnings
  .dockerignore
  contrib/format-httpd/src/test/resources/logback-test.txt
  contrib/storage-cassandra/src/test/resources/queries.cql
  contrib/storage-druid/src/test/resources/druid/docker-compose.yaml
  contrib/storage-druid/src/test/resources/druid/environment.env
  contrib/storage-jdbc/src/test/resources/mysql_config_override/mysql_override.cnf
  contrib/storage-splunk/src/test/resources/logback-test.xml.bak
  hooks/build
  hooks/push
  pom.xml
Labels: code cleanup

#2351 DRILL-1282: Add read and write support for Parquet v2
  common/src/test/java/org/apache/drill/categories/ParquetTest.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/OptionValue.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetFormatConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetGroupScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetReaderConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestFormatPluginOptionExtractor.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetReaderConfig.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestVarlenDecimal.java
Labels: enhancement

#2385 DRILL-8053: Reduce Docker image size
  Dockerfile
  contrib/storage-splunk/pom.xml
  distribution/src/assemble/component.xml
Labels: code cleanup, dependencies

#2386 DRILL-8054: Add SAS Format Plugin
  contrib/format-sas/README.md
  contrib/format-sas/pom.xml
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasBatchReader.java
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasFormatConfig.java
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasFormatPlugin.java
  contrib/format-sas/src/main/resources/bootstrap-format-plugins.json
  contrib/format-sas/src/main/resources/drill-module.conf
  contrib/format-sas/src/test/java/org/apache/drill/exec/store/sas/TestSasReader.java
  contrib/format-sas/src/test/resources/sas/all_rand_normal.sas7bdat
  contrib/format-sas/src/test/resources/sas/date_formats.sas7bdat
  contrib/format-sas/src/test/resources/sas/mixed_data_one.sas7bdat
  contrib/format-sas/src/test/resources/sas/mixed_data_two.sas7bdat
  contrib/format-sas/src/test/resources/sas/time_formats.sas7bdat
  contrib/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  pom.xml
Labels: enhancement, new-format, doc-impacting, reference

#2333 DRILL-8009: DrillConnectionImpl#isValid() doesn't correspond JDBC API
  exec/java-exec/src/main/java/org/apache/drill/exec/client/DrillClient.java
  exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillConnectionImpl.java
  exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillHandler.java
  exec/jdbc/src/test/java/org/apache/drill/jdbc/test/Drill2489CallsAfterCloseThrowExceptionsTest.java
  exec/rpc/src/main/java/org/apache/drill/exec/rpc/BasicClient.java
  exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcBus.java
  exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcConstants.java
Labels: enhancement, Security
