Repository apache/drill, pull requests merged in 2021-06, with the labels that each got.

#2227 DRILL-7928: Add fourth parameter for split_part udf
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestStringFunctions.java
Labels: enhancement

#2229 DRILL-7928: [DOC-UPDATE] Add doc for split_part
  _docs/sql-reference/sql-functions/040-string-manipulation.md
Labels: doc-impacting

#2242 DRILL-7940: Fix Kafka key with avro schema can not displayed correctly
  contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/AvroMessageReader.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaMessageGenerator.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java
Labels: bug

#2243 DRILL-7937: INTERNAL_ERROR when querying Parquet File with decimals
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableFixedByteAlignedReaders.java
Labels: bug

#2247 DRILL-7945: Stop patching newly added Guava methods
  common/src/main/java/org/apache/drill/common/util/GuavaPatcher.java
  common/src/test/java/org/apache/drill/common/util/TestGuavaPatcher.java
  src/main/resources/checkstyle-config.xml
Labels: bug, code cleanup

#2255 DRILL-7947: Unable to aggregate or filter nullable decimals in large record sets
  exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroColumnConverterFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetTableMetadataUtils.java
  exec/vector/src/main/java/org/apache/drill/exec/util/DecimalUtility.java
Labels: bug

#2241 DRILL-7938: Convert JDBC Storage Plugin to EVF
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcBatchCreator.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcBatchReader.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcRecordReader.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcScanBatchCreator.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcSubScan.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcBigintWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcBitWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcColumnWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcDateWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcDoubleWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcFloatWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcIntWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcTimeWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcTimestampWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcVarbinaryWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcVarcharWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/writers/JdbcVardecimalWriter.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithH2IT.java
  pom.xml
Labels: Updates, code cleanup, refactoring

#2245 DRILL-7942 Update Mockito to latest 3.x
  pom.xml
Labels: Updates, dependencies

#2258 Fix typo in XMLBatchReader: "Failed to open ~open~ input file"
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java
Labels: Minor Update, code cleanup

#2253 DRILL-7950: Drill classpath includes both avatica-core:jar:1.15.0 and avatica:jar:1.17.0
  contrib/storage-cassandra/pom.xml
  contrib/storage-elasticsearch/pom.xml
Labels: dependencies

#2252 [DOC UPDATE] Update dead links
  _docs/connect-a-data-source/036-configuring-storage-plugins.md
Labels: documentation

#2254 DRILL-7948: Unable to query file with required fixed_len_byte_array decimal columns
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/AsyncPageReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ColumnReaderFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/FixedByteAlignedReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableFixedByteAlignedReaders.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/PageReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetFixedWidthDictionaryReaders.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/ParquetSimpleTestFileGenerator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetLogicalTypes.java
  exec/java-exec/src/test/resources/parquet/SingleRow_RequiredFixedLength_Decimal.parquet
  exec/java-exec/src/test/resources/parquet/interval_dictionary.parquet
  exec/java-exec/src/test/resources/parquet/nullable_interval_dictionary.parquet
Labels: bug

#2261 DRILL-5177: Use much cheaper estimated record count when determining stats for a mongo scan
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java
Labels: Minor Update

#2262 DRILL-7952: Fix Scan Stats for Mongo Plugin
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java
Labels: Minor Update, bug

#2263 [DOC UPDATE] Wildcard Matching Documentation
  _docs/query-data/query-a-file-system/040-querying-directories.md
Labels: documentation

#2256 DRILL-7951: Add Response Metadata Fields to HTTP Storage Plugin
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ImplicitColumnUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
Labels: doc-impacting, enhancement
