Repository apache/drill, pull requests merged in 2021-02, with the labels that each got.

#2158 DRILL-7850: Unable to load DrillConnectionImpl class from JDBC driver
  exec/java-exec/src/test/java/org/apache/drill/exec/util/StoragePluginTestUtils.java
  exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillConnectionImpl.java
  exec/jdbc/src/test/java/org/apache/drill/jdbc/JdbcTestBase.java
  exec/jdbc/src/test/java/org/apache/drill/jdbc/impl/DrillConnectionUtils.java
  exec/jdbc/src/test/java/org/apache/drill/jdbc/test/TestJdbcQuery.java
Labels: bug

#2117 DRILL-7812: updated hashCode function for MaterializedField
  exec/vector/src/main/java/org/apache/drill/exec/record/MaterializedField.java
  exec/vector/src/test/java/org/apache/drill/exec/record/TestMaterializedField.java
Labels: bug

#2089 Drill-7751: Add Storage Plugin for Splunk
  common/src/test/java/org/apache/drill/categories/SplunkStorageTest.java
  contrib/pom.xml
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/TestKafkaSuit.java
  contrib/storage-splunk/README.md
  contrib/storage-splunk/pom.xml
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkBatchReader.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkConnection.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkGroupScan.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPushDownListener.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkQueryBuilder.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkScanBatchCreator.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkScanSpec.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkSchemaFactory.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkStoragePlugin.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkSubScan.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkUtils.java
  contrib/storage-splunk/src/main/resources/bootstrap-storage-plugins.json
  contrib/storage-splunk/src/main/resources/drill-module.conf
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkBaseTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkConnectionTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkIndexesTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkLimitPushDownTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkPluginTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkQueryBuilderTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSplunkUtils.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java
  contrib/storage-splunk/src/test/resources/logback-test.xml.bak
  contrib/storage-splunk/src/test/resources/test_data.csv
  contrib/storage-splunk/src/test/splunk.md
  distribution/pom.xml
  distribution/src/assemble/component.xml
  pom.xml
Labels: doc-impacting, enhancement, new-storage

#2163 DRILL-7857: Fix misc GitHub Actions failures
  contrib/storage-cassandra/pom.xml
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/BaseCassandraTest.java
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/TestCassandraSuit.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/TestKafkaSuit.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/InteractiveUI.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestRestJson.java
  exec/java-exec/src/test/java/org/apache/drill/exec/util/ExecutorServiceUtilTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/util/TestQueryMemoryAlloc.java
  pom.xml
Labels: code cleanup

#2166 DRILL-7820: Not Supporting Mongo DB Name Capital Letters
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/schema/MongoSchemaFactory.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestConstants.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoDrillIssue.java
Labels: bug

#2167 DRILL-7859: Junit test random failure when the numbers of splunk event was insufficient
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkPluginTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java
Labels: code cleanup

#2174 DRILL-7862: upgrade excel-streaming-reader
  contrib/format-excel/pom.xml
Labels: Minor Update

#2172 Minor Fix: Update the mongo TestSuite list
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
Labels: code cleanup

#2171 DRILL-7861: Add Function to Obtain Inner Map Schemata
  contrib/udfs/README.md
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ComplexSchemaFunctions.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ComplexSchemaUtils.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestComplexSchemaFunctions.java
  contrib/udfs/src/test/resources/json/nestedSchema.json
Labels: doc-impacting, enhancement

#2182 [DOC UPDATE] Format the output to readable for 050-create-view.md
  _docs/sql-reference/sql-commands/050-create-view.md
Labels: documentation

#2170 DRILL-7841: Need to exclude or shade netty lib to avoid [WARNING]
  exec/jdbc-all/pom.xml
Labels: code cleanup

#2169 DRILL-7821: Treat Empty String as NULL in JSON Reader
  exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/fn/JsonReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/vector/complex/writer/TestJsonReader.java
Labels: enhancement
