Repository apache/drill, pull requests merged in 2021-09, with the labels that each got.

#2305 [MINOR-UPDATE] Removed password from debug logging in Python script
  tools/drill-patch-review.py
Labels: Minor Update, Security

#2311 DRILL-7995: Add Oracle HDFS lib to query OCI Object Storage
  distribution/pom.xml
  distribution/src/main/resources/core-site-example.xml
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/ViewExpansionContext.java
  exec/java-exec/src/main/resources/bootstrap-storage-plugins.json
  exec/jdbc-all/pom.xml
  exec/jdbc/pom.xml
  pom.xml
Labels: enhancement, new-storage, dependencies

#2312 Fixed Broken Link for Kafka Plugin Documentation
  contrib/storage-kafka/README.md
Labels: Minor Update

#2315 [TRAVIS CI FIX]: Change clickhouse image to be able to run on both x86-64 and arm64
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithClickhouse.java
Labels: bug, CI

#2322 DRILL-8004: Splunk Sends Newlines in INT Fields, Causing Exceptions
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkBatchReader.java
Labels: bug
