Repository apache/drill, pull requests merged in 2021-04, with the labels that each got.

#2194 DRILL-7888: query.json returns an incorrect error message when the query fails
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/stream/StreamingHttpConnection.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestRestJson.java
  exec/java-exec/src/test/resources/rest/exception.json
  exec/java-exec/src/test/resources/rest/verboseExc.json
Labels: enhancement

#2120 DRILL-7814: Add Limit Pushdown to MongoDB Storage Plugin
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/DruidPushDownFilterForScan.java
  contrib/storage-mongo/pom.xml
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoPushDownFilterForScan.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePlugin.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoSubScan.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestConstants.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoLimitPushDown.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillScanRelBase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillScanRel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/ScanPrel.java
Labels: enhancement

#2195 DRILL-7270 Changed URLs from HTTP to secure HTTPS links and added checksums
  contrib/data/tpch-sample-data/pom.xml
  contrib/storage-kudu/pom.xml
  exec/jdbc-all/pom.xml
  pom.xml
Labels: code cleanup

#2196 DRILL-7894: Large Attributes Crash HDF5 Reader
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5BatchReader.java
Labels: bug

#2197 [DOC-UPDATE] apache-drill-contribution-ideas.md update
  _docs/developer-information/contribute-to-drill/020-apache-drill-contribution-ideas.md
Labels: documentation

#2198 DRILL-7899: Bump checkstyle from 8.16 to 8.29
  pom.xml
Labels: Security, code cleanup

#2199 DRILL-7900: Bump libthrift from 0.13.0 to 0.14.0
  pom.xml
Labels: Security, code cleanup

#2143 DRILL-7825: Unknown logical type <LogicalType UUID:UUIDType()> in Parquet
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ColumnReaderFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet2/DrillParquetGroupConverter.java
  exec/java-exec/src/main/java/org/apache/parquet/hadoop/ParquetColumnChunkPageWriteStore.java
  exec/java-exec/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/ParquetSimpleTestFileGenerator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetComplex.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetLogicalTypes.java
  exec/java-exec/src/test/resources/parquet/parquet_test_file_simple.parquet
  exec/java-exec/src/test/resources/parquet/uuid-simple-fixed-length-array.parquet
  exec/java-exec/src/test/resources/store/parquet/complex/uuid.parquet
  exec/jdbc-all/pom.xml
  pom.xml
Labels: bug, enhancement

#2192 DRILL-7828: Refactor Pcap and Pcapng format plugin
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/PcapBatchReader.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/PcapFormatUtils.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/decoder/Murmur128.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/decoder/Packet.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/decoder/PacketConstants.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/decoder/PacketDecoder.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/decoder/TcpHandshake.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/decoder/TcpSession.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/dto/ColumnDto.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/package-info.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/plugin/BasePcapFormatPlugin.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/plugin/PcapFormatConfig.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/plugin/PcapFormatPlugin.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/plugin/PcapngFormatConfig.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/plugin/PcapngFormatPlugin.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/schema/PcapTypes.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/schema/Schema.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PcapngBatchReader.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PcapngFormatPlugin.java
  contrib/format-pcapng/src/main/resources/bootstrap-format-plugins.json
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/persistent/store/pcap/TestPcapWithPersistentStore.java
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcap/ConcatPcap.java
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcap/TestPcapDecoder.java
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcap/TestPcapEVFReader.java
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcap/TestPcapRecordReader.java
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcap/TestSessionizePCAP.java
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcapng/TestPcapngRecordReader.java
  contrib/format-pcapng/src/test/java/org/apache/drill/exec/store/pcapng/TestPcapngStatRecordReader.java
  contrib/format-pcapng/src/test/resources/config/oldPcapPlugins.json
  contrib/format-pcapng/src/test/resources/pcap/arpWithNullIP.pcap
  contrib/format-pcapng/src/test/resources/pcap/data-1.pcap
  contrib/format-pcapng/src/test/resources/pcap/data-2.pcap
  contrib/format-pcapng/src/test/resources/pcap/dataFromRemote.txt
  contrib/format-pcapng/src/test/resources/pcap/http.pcap
  contrib/format-pcapng/src/test/resources/pcap/synscan.pcap
  contrib/format-pcapng/src/test/resources/pcap/tcp-1.pcap
  contrib/format-pcapng/src/test/resources/pcap/tcp-2.pcap
  contrib/format-pcapng/src/test/resources/pcap/testv1.pcap
  contrib/format-pcapng/src/test/resources/pcapng/example.pcap
  contrib/format-pcapng/src/test/resources/todo/dhcp.pcapng
  contrib/format-pcapng/src/test/resources/todo/dhcp_big_endian.pcapng
  contrib/format-pcapng/src/test/resources/todo/dhcp_little_endian.pcapng
  contrib/format-pcapng/src/test/resources/todo/many_interfaces.pcapng
  contrib/storage-hbase/src/test/java/org/apache/drill/hbase/TestHBaseTableProvider.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/columns/ColumnsScanFramework.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/file/FileScanFramework.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/pcap/PcapFormatConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/pcap/PcapFormatPlugin.java
  exec/java-exec/src/main/resources/bootstrap-storage-plugins.json
  exec/java-exec/src/test/java/org/apache/drill/exec/TestWithZookeeper.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/FormatPluginSerDeTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/sys/TestPStoreProviders.java
  exec/java-exec/src/test/resources/plugins/mock-plugin-upgrade.json
  exec/java-exec/src/test/resources/store/pcap/data-2.pcap
Labels: doc-impacting, refactoring

#2205 DRILL-7910: Bumps commons-io from 2.4 to 2.7
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillRelOptUtil.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/UserClientConnection.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/FilterPushDownStrategy.java
  pom.xml
  tools/drill-patch-review.py
  tools/fmpp/pom.xml
Labels: Minor Update, dependencies

#2201 DRILL-7903: Update mongo driver from 3.12 to 4.2
  contrib/storage-mongo/pom.xml
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/bson/BsonRecordReader.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePlugin.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePluginConfig.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/config/MongoPersistentStoreProvider.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/schema/MongoSchemaFactory.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/bson/TestBsonRecordReader.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestSuite.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoStoragePluginUsesCredentialsStore.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestTableGenerator.java
  exec/java-exec/pom.xml
Labels: Updates, code cleanup

#2206 Add Github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Minor Update, documentation
