Repository apache/drill, pull requests merged in 2022-03, with the labels that each got.

#2419 DRILL-8085: EVF V2 support in the "Easy" format plugin
  contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpFormatPlugin.java
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelFormatPlugin.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5FormatPlugin.java
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogFormatPlugin.java
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/ImageFormatPlugin.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/plugin/BasePcapFormatPlugin.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfFormatPlugin.java
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasFormatPlugin.java
  contrib/format-spss/src/main/java/org/apache/drill/exec/store/spss/SpssFormatPlugin.java
  contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogFormatPlugin.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/ReaderState.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/ClassicScanBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyFileScanBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EvfV1ScanBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/TextFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/log/LogFormatPlugin.java
Labels: code cleanup, refactoring

#2479 DRILL-8153: Convert OAuth REST APIs to JSON
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthTokenUpdate.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/OAuthTokenContainer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
Labels: enhancement, Minor Update

#2474 DRILL-8140: Add JSON Post Body to HTTP Rest Storage Plugin
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
Labels: enhancement, doc-impacting

#2480 DRILL-8154: Upgrade to poi 5.2.1
  contrib/format-excel/pom.xml
Labels: dependencies

#2487 [MINOR UPDATE] Add Stalebot Config
  .github/stale.yml
Labels: Minor Update

#2486 DRILL-8161: Add Global Credentials to HTTP Storage Plugin
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePluginConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthTokenUpdate.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/CredentialProviderUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/UsernamePasswordWithProxyCredentials.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/oauth/OAuthTokenCredentials.java
Labels: enhancement, doc-impacting

#2489 DRILL-8162: Add OpenAPI Specification documentation for Drill's REST API
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/DrillRestServer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/DrillRoot.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/QueryResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StatusResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/jdbc-all/pom.xml
  pom.xml
Labels: enhancement, documentation

#2494 DRILL-8167: Add JSON Config Options to Format Config
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JSONFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JSONRecordReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/DropboxFileSystemTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestFormatPluginOptionExtractor.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/json/TestJsonModes.java
  exec/java-exec/src/test/java/org/apache/drill/test/PhysicalOpUnitTestBase.java
  exec/java-exec/src/test/resources/jsoninput/nan_test.json
Labels: enhancement, doc-impacting

#2495 DRILL-8168: Do not duplicate attempts to impersonate a user in the REST API
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/BaseQueryRunner.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/DrillRestServer.java
Labels: bug

#2496 DRILL-8169: Add UDFs to HTTP Plugin to Facilitate Joins
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
  contrib/storage-http/src/test/resources/data/simple.json
  contrib/storage-http/src/test/resources/data/weather.json
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/UdfUtilities.java
  exec/java-exec/src/test/java/org/apache/drill/test/OperatorFixture.java
Labels: enhancement, doc-impacting

#2497 DRILL-8165: Upgrade liquibase because of CVE-2022-0839
  metastore/rdbms-metastore/pom.xml
  metastore/rdbms-metastore/src/main/java/org/apache/drill/metastore/rdbms/RdbmsMetastore.java
Labels: Security

#2498 DRILL-8171: Convert SequenceFile to EVF2
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileBatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileFormatPlugin.java
Labels: refactoring, Updates

#2485 DRILL-8086: Convert the CSV (AKA "compliant text") reader to EVF V2
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogBatchReader.java
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdLogFormatPlugin.java
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdParser.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JsonRecordWriter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/TextFormatConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/TextFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/CompliantTextBatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/ConstrainedFieldOutput.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/FieldVarCharOutput.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/TextParsingSettings.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/reader/TextReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestTextWriter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/TestRestJson.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/DropboxFileSystemTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/TestPluginRegistry.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestFormatPluginOptionExtractor.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/text/compliant/BaseCsvTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/text/compliant/TestCsvWithHeaders.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/text/compliant/TestCsvWithSchema.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/text/compliant/TestTextReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/mock/TestMockRowReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/util/StoragePluginTestUtils.java
Labels: refactoring, Updates, performance

#2493 DRILL-8164: Upgrade metadata-extractor because of CVE-2022-24613
  contrib/format-image/pom.xml
  contrib/format-image/src/main/java/org/apache/drill/exec/store/image/GenericMetadataReader.java
  contrib/format-image/src/test/resources/image/eps.json
  contrib/format-image/src/test/resources/image/jpeg.json
  contrib/format-image/src/test/resources/image/mov.json
  contrib/format-image/src/test/resources/image/tiff.json
  pom.xml
Labels: Updates, Security, dependencies

#2506 DRILL-8178: Bump AWS Libraries to Latest Version
  distribution/pom.xml
Labels: Minor Update, dependencies

#2505 DRILL-8177: Bump default TLS version to 1.3
  distribution/src/main/resources/drill-override-example.conf
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/ssl/SslContextFactoryConfigurator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfig.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitSSL.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitSSLServer.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/ssl/SslContextFactoryConfiguratorTest.java
Labels: doc-impacting, Security
