Repository apache/drill, pull requests merged in 2022-04, with the labels that each got.

#2512 DRILL-8186: Convert XML format to EVF2
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatConfig.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatPlugin.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
Labels: refactoring, Updates

#2511 DRILL-8174: Convert Avro format to EVF2
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/DynamicSchemaFilter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroBatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/avro/AvroFormatPlugin.java
Labels: bug, refactoring

#2517 DRILL-8191: HTTP Request Function Not Detecting JSON Config
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
Labels: bug, Minor Update

#2519 DRILL-8193: Incorrect Annotation used for HttpJsonOptions
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpJsonOptions.java
Labels: bug, Minor Update

#2522 DRILL-8194: Fix the function of REPLACE throws IndexOutOfBoundsException, if text's length is more than previously applied
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestStringFunctions.java
Labels: bug

#2524 DRILL-8202: Add Options to Skip Malformed JSON Records to HTTP Plugin
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpJsonOptions.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/resources/data/malformed.json
Labels: enhancement, Minor Update
