Repository apache/drill, pull requests merged in 2022-01, with the labels that each got.

#2412 DRILL-8088: Improve expression evaluation performance
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/EvaluationVisitor.java
Labels: enhancement

#2420 DRILL-8090: LIMIT clause is pushed down to an invalid OFFSET-FETCH clause for MS SQL Server
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/rules/JdbcLimitRule.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/rules/JdbcSortRule.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixConvention.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixIntermediatePrelConverterRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcRuleBase.java
  pom.xml
Labels: bug

#2413 DRILL-8089: Separate the setup time for some operators
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/mergereceiver/MergingRecordBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/partitionsender/PartitionSenderRootExec.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectRecordBatch.java
Labels: enhancement

#2359 DRILL-8028: Add PDF Format Plugin
  contrib/format-pdf/README.md
  contrib/format-pdf/pom.xml
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfBatchReader.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfFormatConfig.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfFormatPlugin.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfMetadataReader.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfRowIterator.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfUtils.java
  contrib/format-pdf/src/main/resources/bootstrap-format-plugins.json
  contrib/format-pdf/src/main/resources/drill-module.conf
  contrib/format-pdf/src/test/java/org/apache/drill/exec/store/pdf/TestPdfFormat.java
  contrib/format-pdf/src/test/java/org/apache/drill/exec/store/pdf/TestPdfUtils.java
  contrib/format-pdf/src/test/resources/pdf/20.pdf
  contrib/format-pdf/src/test/resources/pdf/arabic.pdf
  contrib/format-pdf/src/test/resources/pdf/argentina_diputados_voting_record.pdf
  contrib/format-pdf/src/test/resources/pdf/campaign_donors.pdf
  contrib/format-pdf/src/test/resources/pdf/encrypted.pdf
  contrib/format-pdf/src/test/resources/pdf/jpeg2000.pdf
  contrib/format-pdf/src/test/resources/pdf/labor.pdf
  contrib/format-pdf/src/test/resources/pdf/schools.pdf
  contrib/format-pdf/src/test/resources/pdf/spreadsheet_no_bounding_frame.pdf
  contrib/format-pdf/src/test/resources/pdf/twotables.pdf
  contrib/format-pdf/src/test/resources/pdf/us-017.pdf
  contrib/format-pdf/src/test/resources/pdf/us-020.pdf
  contrib/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  distribution/src/main/resources/drill-config.sh
  pom.xml
Labels: enhancement, new-format, doc-impacting, Ready for Review

#2426 DRILL-8106: do not use cellIterator because it skips empty cells
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
  contrib/format-excel/src/test/resources/excel/missing_data.xlsx
Labels: bug

#2428 DRILL-8108: Excel Reader Fails with Duplicate Columns
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
  contrib/format-excel/src/test/resources/excel/dup_col_names.xlsx
Labels: bug, Minor Update

#2416 DRILL-8094: Support reverse truncation for split_part udf
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestStringFunctions.java
Labels: enhancement, doc-impacting, Minor Update, Ready for Review

#2429 DRILL-8107: Hadoop2 backport Maven profile
  common/src/main/java/org/apache/drill/common/util/GuavaPatcher.java
  contrib/storage-phoenix/README.md
  docs/dev/Maven.md
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ColumnDataReader.java
  exec/jdbc-all/pom.xml
  pom.xml
Labels: mvn

#2388 DRILL-8057: INFORMATION_SCHEMA filter push down is inefficient
  exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicRootSchema.java
  exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicSchema.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContextImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/DrillSchemaFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/SchemaTreeProvider.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/FilterEvaluator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaFilter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaRecordGenerator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/mock/MockBreakageStorage.java
  exec/java-exec/src/main/java/org/apache/drill/exec/work/metadata/MetadataProvider.java
  exec/java-exec/src/test/java/org/apache/drill/PlanningBase.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestSchema.java
  exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestInfoSchema.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/ischema/TestInfoSchemaFilterPushDown.java
Labels: code cleanup, performance

#2430 DRILL-8023: Empty dict page breaks the "old" Parquet reader
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/AsyncPageReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/PageReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestEmptyParquet.java
  exec/java-exec/src/test/resources/parquet/empty/empty_dict_page.parquet
Labels: bug

#2424 DRILL-8092: Add Auto Pagination to HTTP Storage Plugin
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/OffsetPaginator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/PagePaginator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/Paginator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPaginator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoader.java
Labels: refactoring, Minor Update

#2435 DRILL-8112: Excel Reader Ignores HeaderRow Config Param
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
Labels: bug, Minor Update

#2434 [MINOR UPDATE] Remove bogus copy paste test of log dir env var.
  drill-yarn/src/test/java/org/apache/drill/yarn/scripts/TestScripts.java
Labels: code cleanup, Minor Update

#2436 DRILL-8114: Prevent applying Iceberg project on non-Iceberg tables
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/plan/IcebergPluginImplementor.java
  contrib/format-iceberg/src/test/java/org/apache/drill/exec/store/iceberg/IcebergQueriesTest.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/MongoPluginImplementor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillRelOptUtil.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/AbstractPluginImplementor.java
Labels: bug

#2442 DRILL-8118: Add Option to Allow Disk Use on Mongo Queries
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePluginConfig.java
  contrib/storage-mongo/src/main/resources/bootstrap-storage-plugins.json
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestBase.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoStoragePluginUsesCredentialsStore.java
Labels: bug, Minor Update

#2443 DRILL-8116: Upgrade Apache Xerces because of CVE-2022-23437
  pom.xml
Labels: Security, dependencies

#2444 DRILL-8118: Add Option to Allow Disk Use on Mongo Queries
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePluginConfig.java
Labels: bug, Minor Update
