Repository apache/drill, pull requests merged in 2022-07, with the labels that each got.

#2586 [MINOR-UPDATE]: Update CodeQL to v2
  .github/workflows/codeql-analysis.yml
Labels: minor-update, ci

#2579 [Minor Update] Add port number in log file for maintenance convenience
  exec/java-exec/src/main/java/org/apache/drill/exec/server/Drillbit.java
Labels: minor-update

#2581 DRILL-8254: upgrade mysql-connectors-java to 8.0.28 due to CVE-2022-21363
  contrib/storage-jdbc/pom.xml
Labels: bug, security, dependencies

#2582 [Minor Update] Split category unit tests due to memory issues
  .github/workflows/ci.yml
  .travis.yml
  common/src/test/java/org/apache/drill/categories/EasyOutOfMemory.java
  common/src/test/java/org/apache/drill/categories/package-info.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/TestDrillbitResilience.java
  pom.xml
Labels: minor-update, ci

#2591 DRILL-8255: Update Drill-Calcite version to include fix for CALCITE-4992
  contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStorageConfig.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticComplexTypesTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticInfoSchemaTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchPlanTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchQueryTest.java
  pom.xml
Labels: bug, dependencies, backport-to-stable

#2594 DRILL-8249: Parquet decoding error reading nation.dict.parquet from test framework
  exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfigServer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ColumnReader.java
Labels: bug, backport-to-stable

#2593 DRILL-8257: Resolve Netty lib conflicts
  contrib/format-maprdb/pom.xml
  contrib/storage-hbase/pom.xml
  contrib/storage-hive/core/pom.xml
  distribution/pom.xml
  exec/java-exec/pom.xml
  exec/rpc/pom.xml
  logical/pom.xml
  metastore/iceberg-metastore/pom.xml
  metastore/metastore-api/pom.xml
  pom.xml
Labels: bug, dependencies, backport-to-stable

#2590 DRILL-8158: Remove non-reproducible build outputs
  docs/dev/Release.md
  exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/VersionIterator.java
  pom.xml
Labels: doc-impacting

#2592 DRILL-8256: Fix unit tests of Kerberos auth in RPC
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/security/AuthenticatorProviderImpl.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitBitKerberos.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberos.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberosEncryption.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestDrillSpnegoAuthenticator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoAuthentication.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoConfig.java
  exec/java-exec/src/test/java/org/apache/drill/test/QueryBuilder.java
Labels: bug, ci, backport-to-stable

#2603 DRILL-8263: upgrade libpam4j due to CVE
  exec/java-exec/pom.xml
Labels: bug, security, dependencies, backport-to-stable

#2606 DRILL-8264: upgrade joda-time
  pom.xml
Labels: dependencies

#2607 DRILL-8262: Remove Xalan Dependency
  exec/java-exec/pom.xml
  exec/jdbc/pom.xml
  pom.xml
Labels: security, dependencies

#2608 DRILL-8266: number narrowing issues
  contrib/storage-hbase/src/test/java/org/apache/drill/hbase/TestTableGenerator.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/NetworkFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/HashTableTemplate.java
  exec/java-exec/src/main/java/org/apache/drill/exec/record/RecordBatchSizer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/record/VectorInitializer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableColumnReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/util/filereader/BufferedDirectBufInputStream.java
  exec/java-exec/src/test/java/org/apache/drill/exec/DrillSeparatePlanningTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestWriter.java
  exec/java-exec/src/test/java/org/apache/drill/test/ProfileParser.java
Labels: backport-to-stable

#2597 DRILL-7960: Column metadata DECIMAL precision can exceed max supported value
  common/src/main/java/org/apache/drill/common/types/Types.java
  exec/java-exec/src/test/java/org/apache/drill/TestUnionAll.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestVarlenDecimal.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/MetadataUtils.java
Labels: bug, backport-to-stable

#2585 DRILL-8235: Add Storage Plugin for Google Sheets
  .gitignore
  common/src/main/java/org/apache/drill/common/Typifier.java
  contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReaderUserAgent.java
  contrib/format-httpd/src/test/resources/httpd/typeremap.httpd
  contrib/native/client/patches/zookeeper-3.4.6-x64.patch
  contrib/native/client/readme.win.txt
  contrib/pom.xml
  contrib/storage-googlesheets/.gitignore
  contrib/storage-googlesheets/README.md
  contrib/storage-googlesheets/pom.xml
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/DrillDataStore.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/DrillDataStoreFactory.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchWriter.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsColumn.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsGroupScan.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsPushDownListener.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsScanBatchCreator.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsScanSpec.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsStoragePlugin.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsStoragePluginConfig.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsSubScan.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsWriter.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsWriterBatchCreator.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/columns/GoogleSheetsColumnRange.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/columns/GoogleSheetsColumnWriter.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsDrillSchema.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsRootSchema.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsSchemaFactory.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsRangeBuilder.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsUtils.java
  contrib/storage-googlesheets/src/main/resources/bootstrap-storage-plugins.json
  contrib/storage-googlesheets/src/main/resources/drill-module.conf
  contrib/storage-googlesheets/src/test/README.md
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetUtils.java
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsLimitPushdown.java
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsWriter.java
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestRangeBuilder.java
  contrib/storage-googlesheets/src/test/resources/data/Drill_Test_Data.xlsx
  distribution/pom.xml
  distribution/src/assemble/component.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/oauth/PersistentTokenTable.java
  exec/java-exec/src/main/java/org/apache/drill/exec/oauth/Tokens.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/oauth/OAuthTokenCredentials.java
  exec/java-exec/src/main/resources/rest/storage/update.ftl
Labels: enhancement, new-storage, doc-impacting

#2613 DRILL-8272: Skip MAP column without children when creating parquet tables
  exec/java-exec/src/main/codegen/templates/AbstractRecordWriter.java
  exec/java-exec/src/main/codegen/templates/EventBasedRecordWriter.java
  exec/java-exec/src/main/codegen/templates/ParquetOutputRecordWriter.java
  exec/java-exec/src/main/codegen/templates/RecordWriter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
Labels: backport-to-stable

#2611 DRILL-8269: Classified metrics for easier maintenance
  common/src/main/java/org/apache/drill/exec/metrics/DrillMetrics.java
  common/src/main/java/org/apache/drill/exec/metrics/MetricsCategory.java
  exec/java-exec/src/main/resources/rest/index.ftl
  exec/java-exec/src/main/resources/rest/metrics/metrics.ftl
  exec/java-exec/src/main/resources/rest/static/css/drillStyle.css
  pom.xml
Labels: enhancement, dependencies, ui

#2610 DRILL-8268: Fix Hadoop 2 and Netty lib exclusions, REST mem limiter disabled by default
  .github/workflows/ci.yml
  contrib/format-maprdb/pom.xml
  contrib/storage-hbase/pom.xml
  contrib/storage-hive/core/pom.xml
  contrib/storage-phoenix/pom.xml
  distribution/pom.xml
  docs/dev/Release.md
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/sequencefile/SequenceFileBatchReader.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/jdbc-all/pom.xml
  pom.xml
  tools/release-scripts/release.sh
Labels: bug, backport-to-stable

#2615 DRILL-8273: Complex typed columns cannot be made implicit
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/project/TestTupleProjection.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/DictColumnMetadata.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/MapColumnMetadata.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/RepeatedListColumnMetadata.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/VariantColumnMetadata.java
Labels: bug, backport-to-stable
