Repository apache/drill, pull requests merged in 2022-10, with the labels that each got.

#2662 DRILL-8321: Change kafka_2.13 dependency scope to test
  contrib/storage-kafka/pom.xml
  contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/MessageIterator.java
Labels: bug, minor-update, dependencies, backport-to-stable, stability

#2666 DRILL-8326: Bump Snakeyaml To 1.33
  pom.xml
Labels: minor-update, dependencies, backport-to-stable

#2669 DRILL-8329: Close HTTP Caching Resources
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
Labels: bug, minor-update, backport-to-stable, stability

#2670 DRILL-8330: Convert ESRI Shape File Reader to EVF2
  contrib/format-esri/pom.xml
  contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpBatchReader.java
  contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpFormatPlugin.java
Labels: code-cleanup, refactoring, minor-update

#2664 DRILL-8325: Convert PDF Format Plugin to EVF V2
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfBatchReader.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfFormatPlugin.java
  contrib/format-pdf/src/test/java/org/apache/drill/exec/store/pdf/TestPdfFormat.java
Labels: code-cleanup, refactoring, minor-update

#2667 DRILL-8327: GoogleSheets not Reporting Schemata to Info_Schema
  contrib/storage-googlesheets/.gitignore
  contrib/storage-googlesheets/README.md
  contrib/storage-googlesheets/pom.xml
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/DrillDataStore.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsStoragePlugin.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsDrillSchema.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsRootSchema.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsSchemaFactory.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsUtils.java
  contrib/storage-googlesheets/src/main/resources/bootstrap-storage-plugins.json
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java
Labels: bug, enhancement, doc-impacting

#2668 DRILL-8328: HTTP UDF Not Resolving Storage Aliases
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFWithAliases.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/QueryContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillOptiq.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/PlannerSettings.java
  exec/java-exec/src/main/java/org/apache/drill/exec/work/metadata/ServerMetaProvider.java
  exec/java-exec/src/test/java/org/apache/drill/PlanningBase.java
Labels: bug, security, access-controls, backport-to-stable

#2672 MINOR UPDATE: HDF5 README lists 4 conf. vars. while it says 3.
  contrib/format-hdf5/README.md
Labels: documentation, minor-update

#2674 DRILL-8332: upgrade to jackson 2.13.4.20221012
  pom.xml
Labels: minor-update, security, backport-to-stable

#2677 DRILL-8332: upgrade jackson due to issue in gradle module
  pom.xml
Labels: minor-update, security, dependencies, backport-to-stable

#2676 [MINOR UPDATE]: Upgrade org.freemarker:freemarker to 2.3.30
  pom.xml
Labels: minor-update, security, dependencies, backport-to-stable

#2675 [MINOR UPDATE]: Upgrade org.apache.kafka:kafka_2.13 to 2.8.2
  contrib/storage-kafka/pom.xml
Labels: minor-update, security, dependencies, backport-to-stable

#2678 DRILL-8333: Resource leak when JsonLoader is built from a stream
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpUdfUtils.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/JsonMessageReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/ClosingStreamIterator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
Labels: bug, backport-to-stable

#2682 fix(sec): upgrade com.drewnoakes:metadata-extractor to 2.18.0
  contrib/format-image/pom.xml
Labels: minor-update, security, dependencies, backport-to-stable

#2665 DRILL-8324: sizeof refactor
  contrib/storage-opentsdb/pom.xml
  contrib/storage-opentsdb/src/main/java/org/apache/drill/exec/store/openTSDB/OpenTSDBGroupScan.java
  contrib/storage-opentsdb/src/main/java/org/apache/drill/exec/store/openTSDB/SizeEstimator.java
  contrib/storage-opentsdb/src/test/java/org/apache/drill/exec/store/openTSDB/TestDataHolder.java
  contrib/storage-opentsdb/src/test/java/org/apache/drill/exec/store/openTSDB/TestOpenTSDBPlugin.java
  contrib/storage-opentsdb/src/test/java/org/apache/drill/exec/store/openTSDB/TestSizeEstimator.java
Labels: code-cleanup, dependencies, backport-to-stable

#2655 DRILL-8314: Add support for automatically retrying and disabling broken storage plugins
  .editorconfig
  common/src/main/java/org/apache/drill/common/exceptions/UserException.java
  contrib/native/client/src/protobuf/UserBitShared.pb.cc
  contrib/native/client/src/protobuf/UserBitShared.pb.h
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/DruidStoragePlugin.java
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseStoragePlugin.java
  contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveStoragePlugin.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/CapitalizingJdbcSchema.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DefaultJdbcDialect.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcConventionFactory.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcDialectFactory.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcInsertWriterBatchCreator.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcIntermediatePrel.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcIntermediatePrelConverterRule.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcPrel.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcRecordWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStoragePlugin.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcTableModifyWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcWriterBatchCreator.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/clickhouse/ClickhouseJdbcDialect.java
  contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaStoragePlugin.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixStoragePlugin.java
  exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicRootSchema.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillSqlWorker.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/AbstractStoragePlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/base/filter/FilterPushDownStrategy.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaStoragePlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/util/FileSystemUtil.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestSchema.java
  exec/java-exec/src/test/java/org/apache/drill/exec/util/FileSystemUtilTest.java
  protocol/src/main/java/org/apache/drill/exec/proto/UserBitShared.java
  protocol/src/main/protobuf/UserBitShared.proto
Labels: stability

#2684 DRILL-8337: Upgrade Hive libs to 3.1.3 due to sonatype-2019-0400
  contrib/storage-hive/core/pom.xml
  pom.xml
Labels: security, dependencies, backport-to-stable

#2685 DRILL-8338: Upgrade jQuery to 3.6.1 and DataTables to 1.12.1 due to sonatype-2020-0988
  drill-yarn/src/main/resources/drill-am/generic.ftl
  exec/java-exec/src/main/resources/rest/generic.ftl
  exec/java-exec/src/main/resources/rest/options.ftl
  exec/java-exec/src/main/resources/rest/profile/profile.ftl
  exec/java-exec/src/main/resources/rest/query/result.ftl
  exec/java-exec/src/main/resources/rest/static/README.datatables.md
  exec/java-exec/src/main/resources/rest/static/css/dataTables.colVis-1.1.0.min.css
  exec/java-exec/src/main/resources/rest/static/css/dataTables.jqueryui.css
  exec/java-exec/src/main/resources/rest/static/css/datatables.min.css
  exec/java-exec/src/main/resources/rest/static/css/jquery-ui-1.10.3.min.css
  exec/java-exec/src/main/resources/rest/static/js/dataTables.colVis-1.1.0.min.js
  exec/java-exec/src/main/resources/rest/static/js/datatables.min.js
  exec/java-exec/src/main/resources/rest/static/js/jquery-3.6.0.min.js
  exec/java-exec/src/main/resources/rest/static/js/jquery-3.6.1.min.js
  exec/java-exec/src/main/resources/rest/static/js/jquery.dataTables-1.10.0.min.js
  exec/java-exec/src/main/resources/rest/static/js/jquery.dataTables-1.10.16.min.js
Labels: security, ui, backport-to-stable

#2680 DRILL-8335: Add Ability to Query GoogleSheets Tabs by Index
  contrib/storage-googlesheets/README.md
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/DrillDataStore.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsDrillSchema.java
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java
Labels: enhancement

#2690 DRILL-8341: Add Scanned Plugin List to Sys Profiles Table
  exec/java-exec/src/main/java/org/apache/drill/exec/store/sys/ProfileInfoIterator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/work/metadata/TestMetadataProvider.java
Labels: doc-impacting, minor-update

#2691 DRILL-8342: Add Automatic Retry for Rate Limited APIs
  contrib/storage-http/Pagination.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePluginConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFWithAliases.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthTokenUpdate.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestProvidedSchema.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestUserTranslationInHttpPlugin.java
Labels: enhancement, doc-impacting
