Repository apache/drill, pull requests merged in 2022-08, with the labels that each got.

#2620 DRILL-8273: Complex typed columns cannot be made implicit (extend unit tests)
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/project/TestTupleProjection.java
Labels: bug, backport-to-stable

#2619 DRILL-8277: Publish SNAPSHOT artifacts to the Apache snapshots repo from CI
  .github/workflows/publish-snapshot.yml
Labels: ci

#2621 DRILL-8278: The period character '.' is broken in SQL LIKE patterns
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/RegexpUtil.java
  exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestSqlPatterns.java
Labels: bug, backport-to-stable

#2618 DRILL-8276: Add Support for User Translation for Splunk Plugin
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkBatchReader.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkConnection.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkGroupScan.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkScanSpec.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkSchemaFactory.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkStoragePlugin.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkSubScan.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkConnectionTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkPluginTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/TestSplunkUserTranslation.java
  pom.xml
Labels: enhancement, doc-impacting, security, dependencies

#2622 DRILL-8279: Use thick Phoenix driver
  .github/workflows/ci.yml
  contrib/storage-hive/core/pom.xml
  contrib/storage-phoenix/README.md
  contrib/storage-phoenix/pom.xml
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixDataSource.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixReader.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixStoragePlugin.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixStoragePluginConfig.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixImplementor.java
  contrib/storage-phoenix/src/main/resources/bootstrap-storage-plugins.json
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixBaseTest.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixBasicsIT.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixSQLTest.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/PhoenixTestSuite.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/ImpersonationPhoenixIT.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/PhoenixEnvironment.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixBaseTest.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixCommandTest.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixDataTypeTest.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixSQLTest.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixTestSuite.java
  contrib/storage-phoenix/src/test/resources/hbase-site.xml
Labels: bug, backport-to-stable

#2625 DRILL-8280: Cannot ANALYZE files containing non-ASCII column names
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/SchemaFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestMetastoreCommands.java
Labels: bug, backport-to-stable

#2627 DRILL-8281: Info schema LIKE with ESCAPE push down bug
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/InfoSchemaFilter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestInfoSchema.java
Labels: bug, backport-to-stable

#2630 DRILL-8282: Bump Hadoop-Common Version to 3.2.4 (CVE)
  contrib/storage-hbase/pom.xml
  contrib/storage-hive/core/pom.xml
  distribution/pom.xml
  drill-yarn/pom.xml
  exec/java-exec/pom.xml
  exec/rpc/pom.xml
  exec/vector/pom.xml
  logical/pom.xml
  metastore/iceberg-metastore/pom.xml
  metastore/metastore-api/pom.xml
  pom.xml
Labels: security, dependencies

#2635 DRILL-8282: Update hadoop.dll and winutils.exe to 3.2.4.
  distribution/src/main/resources/winutils/hadoop.dll
  distribution/src/main/resources/winutils/winutils.exe
Labels: updates, backport-to-stable

#2633 DRILL-8287: Add Support for Keyset Based Pagination
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsStoragePluginConfig.java
  contrib/storage-http/Pagination.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpGroupScan.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpPaginatorConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/IndexPaginator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/OffsetPaginator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/PagePaginator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/Paginator.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
  contrib/storage-http/src/test/resources/data/index_response1.json
  contrib/storage-http/src/test/resources/data/index_response2.json
  contrib/storage-http/src/test/resources/data/index_response3.json
  contrib/storage-http/src/test/resources/data/index_response4.json
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/RowBatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/TupleParser.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/DummyValueParser.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/JsonStructureParser.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/SimpleMessageParser.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/BigIntListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/BooleanListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/DateValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/DecimalValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/DoubleListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/IntervalValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/ScalarListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/StrictBigIntValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/StrictDoubleValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/StrictIntValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/StrictStringValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/TimeValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/TimestampValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/UtcDateValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/UtcTimestampValueListener.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/values/VarCharListener.java
Labels: bug, enhancement, doc-impacting, json
