Repository apache/drill, pull requests merged in 2022-02, with the labels that each got.

#2441 DRILL-8115: Adds LIMIT pushdown support in the scan framework
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/RowBatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/ScanOperatorEvents.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/ScanOperatorExec.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/framework/ManagedScanFramework.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/framework/SchemaNegotiator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/framework/SchemaNegotiatorImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/framework/ShimBatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/project/ReaderSchemaOrchestrator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/project/ScanSchemaOrchestrator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/ScanLifecycleBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/ReaderLifecycle.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/ScanLifecycle.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/SchemaNegotiatorImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/ResultSetLoader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/RowSetLoader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ResultSetLoaderImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ResultSetOptionBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/RowSetLoaderImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/WriterIndexImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/mock/ExtendedMockBatchReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/BaseScanOperatorExecTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/TestScanOperExecBasics.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/TestScanOperExecEarlySchema.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/TestScanOperExecLimit.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/TestScanOperExecOverflow.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/TestScanLimit.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/BaseTestScanLifecycle.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/TestScanLifecycleLimit.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/impl/TestResultSetLoaderLimits.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/resultSet/impl/TestResultSetLoaderProtocol.java
  exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/writer/WriterEvents.java
Labels: enhancement, refactoring, performance

#2433 DRILL-8111: Remove lombok usage
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergBlockMapBuilder.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergGroupScan.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergSubScan.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergWork.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatMatcher.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatPlugin.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/format/IcebergFormatPluginConfig.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/plan/DrillExprToIcebergTranslator.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/read/IcebergRecordReader.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotAfter.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotByTime.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotFactory.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/snapshot/SnapshotsBetween.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfFormatConfig.java
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasFormatConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpJsonOptions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpPaginatorConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/oauth/AccessTokenAuthenticator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/oauth/AccessTokenInterceptor.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcWriterField.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/BaseMongoSubScanSpec.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoFilterBuilder.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoGroupScan.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoScanSpec.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePluginConfig.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoSubScan.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixDataSource.java
  contrib/storage-phoenix/src/test/java/org/apache/drill/exec/store/phoenix/secured/SecuredPhoenixBaseTest.java
  distribution/src/assemble/component.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/alias/ResolvedAliases.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/BaseAliasHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/CreateAliasHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DropAliasHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DropAllAliasesHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/SqlCreateAlias.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/SqlDropAlias.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/SqlDropAllAliases.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/user/security/VaultUserAuthenticator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableRecordReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetFormatConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginConverterRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/testing/Injection.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/sys/PStoreTestUtil.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/sys/TestPStoreProviders.java
  lombok.config
  pom.xml
Labels: code cleanup, dependencies

#2432 DRILL-7994: Dependency version updates for severe vulnerabilities
  .github/workflows/ci.yml
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
  contrib/storage-jdbc/pom.xml
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/CapitalizingJdbcSchema.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcRecordWriter.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/utils/CreateTableStmtBuilder.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestCreateTableStmtBuilder.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithH2IT.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithH2.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithMySQL.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithPostgres.java
  contrib/storage-jdbc/src/test/resources/h2-test-data.sql
  contrib/storage-jdbc/src/test/resources/h2_information_schema_tables.csv
  distribution/pom.xml
  distribution/src/assemble/component.xml
  distribution/src/main/resources/LICENSE
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DropTableHandler.java
  exec/java-exec/src/main/java/org/apache/parquet/hadoop/ColumnChunkIncReadStore.java
  exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestAnalyze.java
  exec/java-exec/src/test/java/org/apache/drill/storage/CredentialsProviderSerDeTest.java
  exec/jdbc-all/pom.xml
  exec/memory/base/src/main/java/io/netty/buffer/DrillBuf.java
  pom.xml
Labels: Security

#2431 DRILL-8109: Hive storage plugin support reading parquet timestamp type with int64 logical type
  contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/writers/primitive/HiveTimestampWriter.java
  contrib/storage-hive/core/src/test/java/org/apache/drill/exec/store/hive/data/TestHiveDataWriter.java
Labels: bug

#2450 DRILL-8123: Revise scan limit pushdown
  contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
  contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReader.java
  contrib/format-sas/src/test/java/org/apache/drill/exec/store/sas/TestSasReader.java
  contrib/format-syslog/src/test/java/org/apache/drill/exec/store/syslog/TestSyslogFormat.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractBase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyGroupScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasySubScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/text/TextFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetGroupScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetWriterBatchCreator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/metastore/TestMetastoreWithEasyFormatPlugin.java
Labels: enhancement, code cleanup, refactoring

#2451 DRILL-8124: Fix implicit column issue with EVF 2
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/file/ImplicitColumnMarker.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/file/ImplicitColumnResolver.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/OutputBatchBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/AbstractSchemaTracker.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/MutableTupleSchema.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/validate/IteratorValidatorBatchIterator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/record/VectorContainer.java
Labels: bug, code cleanup

#2453 DRILL-8126: Ignore OAuth Parameter in Storage Plugin
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java
Labels: bug, Minor Update

#2457 DRILL-8129: Storage-phoenix cannot resolve OSGi bundle apache-ds.jdbm1
  contrib/storage-phoenix/pom.xml
  exec/jdbc-all/pom.xml
Labels: bug, Minor Update

#2458 DRILL-8130: Upgrade Hadoop 2 to 2.10.1 because of CVE-2020-9492
  exec/jdbc-all/pom.xml
  pom.xml
Labels: Security

#2459 DRILL-8131: Infinite planning when JDBC or Phoenix plugin is enabled
  contrib/storage-jdbc/pom.xml
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/DrillJdbcConvention.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/rules/JdbcLimitRule.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMySQLIT.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixConvention.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillLimitRelBase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillLimitRel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/LimitPrel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcRuleBase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rel/PluginLimitRel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginLimitRule.java
Labels: bug

#2462 DRILL-8137: Prevent reading union inputs after cancellation request
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/union/UnionAllRecordBatch.java
  exec/java-exec/src/test/java/org/apache/drill/TestUnionAll.java
Labels: bug

#2456 DRILL-8122: Change kafka metadata obtaining due to KAFKA-5697
  contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/KafkaGroupScan.java
  contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/MessageIterator.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java
Labels: code cleanup, Updates

#2460 DRILL-8134: Cannot query Parquet INT96 columns as timestamps
  contrib/storage-jdbc/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/BatchReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/FixedByteAlignedReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableColumnReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableFixedByteAlignedReaders.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/PageReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetFixedWidthDictionaryReaders.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
Labels: bug

#2463 DRILL-8139: Data corruption and occasional segfaults querying Parquet/gzip under the async column reader and sync page reader
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/compression/AirliftBytesInputCompressor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/compression/DrillCompressionCodecFactory.java
  pom.xml
Labels: bug, blocked

#2468 DRILL-8142: SAS Reader Returns NPE
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasBatchReader.java
Labels: bug

#2469 DRILL-8143: Error querying json with $date field
  distribution/src/main/resources/sqlline.bat
  exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/fn/VectorOutput.java
  exec/java-exec/src/test/resources/jsoninput/input2.json
Labels: bug

#2470 DRILL-8144: Cannot launch Drill 1.20 RC 4 on Windows
  distribution/src/main/resources/sqlline.bat
  distribution/src/main/resources/winutils/hadoop.dll
  distribution/src/main/resources/winutils/winutils.exe
  docs/dev/HadoopWinutils.md
  exec/java-exec/pom.xml
  exec/jdbc-all/pom.xml
  pom.xml
Labels: bug

#2472 DRILL-8146: SAS reader fails to read the majority of sas files
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasBatchReader.java
  contrib/format-sas/src/test/java/org/apache/drill/exec/store/sas/TestSasReader.java
Labels: bug

#2454 Add jackson-bom
  exec/java-exec/pom.xml
  exec/jdbc/pom.xml
  pom.xml
Labels: dependencies

#2473 DRILL-8148: Add REST Endpoints to Update OAuth Tokens
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthTokenUpdate.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
Labels: enhancement, doc-impacting
