Repository apache/drill, pull requests merged in 2022-09, with the labels that each got.

#2634 DRILL-8289: Add Threat Hunting Functions
  contrib/udfs/README.md
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/ThreatHuntingFunctions.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestThreatHuntingFunctions.java
Labels: enhancement, doc-impacting, udf

#2617 DRILL-8275: Prevent the JDBC Client from creating spurious paths in Zookeeper
  exec/java-exec/src/main/java/org/apache/drill/exec/coord/zk/ZKClusterCoordinator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/Drillbit.java
  exec/java-exec/src/test/java/org/apache/drill/exec/client/DrillClientStateTest.java
Labels: bug, backport-to-stable

#2639 DRILL-8291: Allow Case Sensitive Filters in HTTP Plugin
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpPushDownListener.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
Labels: bug, backport-to-stable

#2632 DRILL-8283: Add a configurable recursive file listing size limit
  distribution/src/main/resources/core-site-example.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/util/FileSystemUtil.java
  exec/java-exec/src/test/java/org/apache/drill/exec/util/FileSystemUtilTest.java
Labels: security, backport-to-stable, stability

#2643 DRILL-8300: Upgrade to snakeyaml 1.31 due to cve
  pom.xml
Labels: security, dependencies

#2631 [MINOR UPDATE]: Disable lgtm build
  .lgtm.yml
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5ByteDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5DoubleDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5FloatDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5IntDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5LongDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5SmallIntDataWriter.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/writers/HDF5TimestampDataWriter.java
  contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/TableFormatPluginConfig.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStorageConfig.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/CryptoFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/CollectListMapsAggFunction.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/SchemaFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/record/DeadBuf.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/CredentialResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/OAuthRequests.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/vector/src/main/java/org/apache/drill/exec/record/metadata/AbstractPropertied.java
  exec/vector/src/main/java/org/apache/drill/exec/util/JsonStringArrayList.java
  exec/vector/src/main/java/org/apache/drill/exec/util/JsonStringHashMap.java
  pom.xml
Labels: minor-update, backport-to-stable

#2641 DRILL-8295: Probable resource leak in the HTTP storage plugin
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/http/oauth/OAuthUtils.java
Labels: bug, backport-to-stable

#2640 DRILL-8293: Add a docker-compose file to run Drill in cluster mode
  distribution/docker-cluster-mode/Dockerfile
  distribution/docker-cluster-mode/README
  distribution/docker-cluster-mode/docker-compose.yml
  distribution/docker-cluster-mode/drill-override.conf
  distribution/docker-cluster-mode/logback.xml
Labels: backport-to-stable

#2645 DRILL-8302: Tidy up some char conversions
  contrib/format-esri/src/main/java/org/apache/drill/exec/store/esri/ShpBatchReader.java
  contrib/format-iceberg/src/main/java/org/apache/drill/exec/store/iceberg/IcebergWork.java
  contrib/format-maprdb/src/main/java/org/apache/drill/exec/planner/index/MapRDBStatistics.java
  contrib/format-maprdb/src/test/java/com/mapr/drill/maprdb/tests/index/TableIndexCmd.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/rest/DruidQueryClientTest.java
  contrib/storage-kudu/src/main/codegen/templates/KuduRecordWriter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/CharSequenceWrapper.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java
  exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestSqlPatterns.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestCastFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/record/vector/TestValueVector.java
  exec/vector/src/main/codegen/templates/VariableLengthVectors.java
  exec/vector/src/main/java/org/apache/drill/exec/util/Text.java
  exec/vector/src/test/java/org/apache/drill/exec/record/TestMaterializedField.java
Labels: code-cleanup

#2647 DRILL-8304: Update Calcite to 1.32.0
  contrib/storage-cassandra/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/compile/JaninoClassCompiler.java
  pom.xml
Labels: calcite-update

#2642 [MINOR-UPDATE] fix some issues highlighted in lgtm.com
  common/src/main/java/org/apache/drill/common/config/DrillProperties.java
  contrib/storage-kudu/src/main/java/org/apache/drill/exec/store/kudu/KuduGroupScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/ClassGenerator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/FunctionGenerationHelper.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/MergeJoinBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/index/generators/AbstractIndexPlanGenerator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/schema/ListSchema.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/Drillbit.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/profile/OperatorWrapper.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableColumnReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/util/filereader/BufferedDirectBufInputStream.java
Labels: code-cleanup, minor-update

#2648 DRILL-8305: Add Implicit Fields to Google Sheets Reader
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsColumn.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsRangeBuilder.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsUtils.java
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java
Labels: enhancement, doc-impacting

#2649 DRILL-8300: Upgrade snakeyaml to 1.32
  pom.xml
Labels: updates, security, dependencies

#2612 DRILL-8271: Make Storage and Format Config Case Insensitive
  logical/src/main/java/org/apache/drill/common/logical/FormatPluginConfig.java
  logical/src/main/java/org/apache/drill/common/logical/StoragePluginConfig.java
Labels: stability

#2650 DRILL-8307: Ensure thread safety in the Druid plugin HTTP client
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/rest/DruidAdminClient.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/rest/DruidQueryClient.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/rest/RestClient.java
  contrib/storage-druid/src/main/java/org/apache/drill/exec/store/druid/rest/RestClientWrapper.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/DruidTestBase.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/DruidTestSuite.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/TestDataGenerator.java
  contrib/storage-druid/src/test/java/org/apache/drill/exec/store/druid/rest/DruidQueryClientTest.java
Labels: bug, backport-to-stable

#2651 DRILL-8308: Upgrade POI to 5.2.3
  contrib/format-excel/pom.xml
  pom.xml
Labels: minor-update, dependencies, backport-to-stable

#2638 DRILL-8136: Overhaul implict type casting logic
  exec/java-exec/src/main/codegen/data/NumericTypes.tdd
  exec/java-exec/src/main/codegen/templates/NumericFunctionsTemplates.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/ExpressionTreeMaterializer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/ByteArrayFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/ByteSubstring.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/SchemaFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/JoinUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/union/UnionAllRecordBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillRelOptUtil.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillCalciteSqlBetweenOperatorWrapper.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/TypeInferenceUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/resolver/DefaultFunctionResolver.java
  exec/java-exec/src/main/java/org/apache/drill/exec/resolver/ExactFunctionResolver.java
  exec/java-exec/src/main/java/org/apache/drill/exec/resolver/ResolverTypePrecedence.java
  exec/java-exec/src/main/java/org/apache/drill/exec/resolver/TypeCastRules.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetTableMetadataUtils.java
  exec/java-exec/src/test/java/org/apache/drill/TestImplicitCasting.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestReverseImplicitCast.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/json/TestJsonReaderFns.java
  exec/java-exec/src/test/resources/functions/cast/two_way_implicit_cast.json
  protocol/src/main/java/org/apache/drill/common/types/TypeProtos.java
  protocol/src/main/protobuf/Types.proto
Labels: enhancement, doc-impacting

#2653 DRILL-8310: Convert Syslog Format to EVF V2
  contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogBatchReader.java
  contrib/format-syslog/src/main/java/org/apache/drill/exec/store/syslog/SyslogFormatPlugin.java
Labels: code-cleanup, refactoring, minor-update

#2656 DRILL-8315: Convert SAS Format Plugin to EVF V2
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasBatchReader.java
  contrib/format-sas/src/main/java/org/apache/drill/exec/store/sas/SasFormatPlugin.java
Labels: code-cleanup, refactoring, updates, minor-update

#2654 DRILL-8311: Convert SPSS Format Plugin to EVF V2
  contrib/format-spss/src/main/java/org/apache/drill/exec/store/spss/SpssBatchReader.java
  contrib/format-spss/src/main/java/org/apache/drill/exec/store/spss/SpssFormatPlugin.java
Labels: code-cleanup, refactoring, minor-update, dependencies

#2652 DRILL-8190: Fix mongo project pushdown for queries with joins
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcIntermediatePrelConverterRule.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/MongoPluginImplementor.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoProjectPushDown.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/rules/PhoenixIntermediatePrelConverterRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdDistinctRowCount.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdMaxRowCount.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdRowCount.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdSelectivity.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/ColumnConverterFactoryProvider.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/DynamicTypeResolverBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableBatchCreator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/EnumerableSubScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/EnumerableIntermediatePrelConverterRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/VertexDrel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rel/PluginAggregateRel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rel/StoragePluginTableScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginIntermediatePrelConverterRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/util/Utilities.java
Labels: bug, backport-to-stable

#2660 DRILL-8320: Prevent Infinite Pagination for Index Paginator
  contrib/storage-http/.gitignore
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpPaginatorConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/IndexPaginator.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
  contrib/storage-http/src/test/resources/data/nested_pagination_fields.json
  contrib/storage-http/src/test/resources/data/nested_pagination_fields2.json
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/JsonStructureParser.java
Labels: bug

#2663 DRILL-8323: upgrade commons-text to 1.10.0
  contrib/format-excel/pom.xml
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestStringDistanceFunctions.java
  pom.xml
Labels: minor-update, dependencies, backport-to-stable
