Repository apache/drill, pull requests merged in 2022-12, with the labels that each got.

#2715 DRILL-8365: HTTP Plugin Places Parameters in Wrong Place
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
Labels: bug, minor-update, backport-to-stable

#2716 DRILL-8366: Late release of compressor memory in the Parquet writer
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
Labels: bug, backport-to-stable

#2717 DRILL-8368: Update Yauaa to 7.9.0
  pom.xml
Labels: minor-update, dependencies, backport-to-stable

#2713 DRILL-8359: Add mount and unmount command support to the filesystem plugin
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/AbstractStoragePlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ClassicConnectorLocator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemPlugin.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/main/resources/rest/static/js/serverMessage.js
  exec/java-exec/src/test/java/org/apache/drill/exec/store/BoxFileSystemTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/dfs/TestMountCommand.java
Labels: enhancement, doc-impacting

#2725 DRILL-8179: Convert LTSV Format Plugin to EVF2
  contrib/format-ltsv/README.md
  contrib/format-ltsv/pom.xml
  contrib/format-ltsv/src/main/java/org/apache/drill/exec/store/ltsv/LTSVBatchReader.java
  contrib/format-ltsv/src/main/java/org/apache/drill/exec/store/ltsv/LTSVFormatPlugin.java
  contrib/format-ltsv/src/main/java/org/apache/drill/exec/store/ltsv/LTSVFormatPluginConfig.java
  contrib/format-ltsv/src/main/java/org/apache/drill/exec/store/ltsv/LTSVRecordReader.java
  contrib/format-ltsv/src/test/java/org/apache/drill/exec/store/ltsv/TestLTSVQueries.java
  contrib/format-ltsv/src/test/java/org/apache/drill/exec/store/ltsv/TestLTSVRecordReader.java
Labels: code-cleanup, refactoring, doc-impacting, minor-update
