Repository apache/drill, pull requests merged in 2022-11, with the labels that each got.

#2696 DRILL-8348: Cannot delete disabled storage plugins
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsStoragePlugin.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/oauth/OAuthTokenProvider.java
  exec/java-exec/src/main/java/org/apache/drill/exec/oauth/PersistentTokenRegistry.java
  exec/java-exec/src/main/java/org/apache/drill/exec/oauth/TokenRegistry.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/DrillbitContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/OAuthRequests.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/java-exec/src/main/resources/rest/storage/update.ftl
Labels: bug, backport-to-stable

#2695 DRILL-8349: GoogleSheets Not Registering Schemas with Non Default Name
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsSchemaFactory.java
Labels: bug

#2697 DRILL-8299: HashMap key type mismatch in MetadataContext
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/MetadataContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/metadata/Metadata.java
Labels: bug, backport-to-stable

#2698 DRILL-8350: Convert PCAP Format Plugin to EVF2
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/PcapBatchReader.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcap/plugin/BasePcapFormatPlugin.java
  contrib/format-pcapng/src/main/java/org/apache/drill/exec/store/pcapng/PcapngBatchReader.java
Labels: code-cleanup, refactoring, minor-update, stability

#2699 DRILL-8238: Translation of IS NOT NULL($1) is not supported by MongoProject
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/plan/RexToMongoTranslator.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/MongoTestConstants.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoFilterPushDown.java
  contrib/storage-mongo/src/test/java/org/apache/drill/exec/store/mongo/TestMongoProjectPushDown.java
Labels: bug, backport-to-stable

#2700 DRILL-8296: Possible type mismatch bug in SplunkBatchReader
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkBatchReader.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkQueryBuilder.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkUtils.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSplunkUtils.java
Labels: bug, backport-to-stable

#2703 DRILL-8354: Add IS_EMPTY Function
  exec/java-exec/src/main/codegen/templates/IsEmptyDataFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/IsEmptyScalarFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/IsEmptyUtils.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestIsEmptyFunctions.java
  exec/java-exec/src/test/resources/jsoninput/is_empty_tests.json
Labels: enhancement, doc-impacting

#2704 DRILL-8356: Add File Name to GoogleSheets Plugin
  contrib/storage-googlesheets/README.md
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsScanSpec.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsDrillSchema.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsRootSchema.java
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsQueries.java
Labels: enhancement, doc-impacting, minor-update

#2705 DRILL-8357: Add new config options to the Splunk storage plugin
  contrib/storage-splunk/pom.xml
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkConnection.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkConnectionTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkIndexesTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkPluginTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java
  exec/java-exec/src/main/resources/drill-module.conf
Labels: enhancement, doc-impacting

#2689 DRILL-8340: Add Additional Date Manipulation Functions
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DateConversionUtils.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DateFunctions.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DateUtilFunctions.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDateFunctions.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDateUtils.java
  exec/java-exec/src/main/codegen/data/ExtractTypes.tdd
  exec/java-exec/src/main/codegen/templates/DateIntervalFunctionTemplates/Extract.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillOptiq.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/TypeInferenceUtils.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestNewDateFunctions.java
  exec/vector/src/main/java/org/apache/drill/exec/vector/DateUtilities.java
Labels: enhancement, doc-impacting

#2702 DRILL-8353: Format plugin for Delta Lake
  contrib/format-deltalake/README.md
  contrib/format-deltalake/pom.xml
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/DeltaGroupScan.java
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/DeltaParquetTableMetadataProvider.java
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/DeltaRowGroupScan.java
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/format/DeltaFormatMatcher.java
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/format/DeltaFormatPlugin.java
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/format/DeltaFormatPluginConfig.java
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/plan/DeltaPluginImplementor.java
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/plan/DrillExprToDeltaTranslator.java
  contrib/format-deltalake/src/main/java/org/apache/drill/exec/store/delta/read/DeltaScanBatchCreator.java
  contrib/format-deltalake/src/main/resources/bootstrap-format-plugins.json
  contrib/format-deltalake/src/main/resources/drill-module.conf
  contrib/format-deltalake/src/test/java/org/apache/drill/exec/store/delta/DeltaQueriesTest.java
  contrib/format-deltalake/src/test/resources/data-reader-nested-struct/.part-00000-f2547b28-9219-4628-8462-cc9c56edfebb-c000.snappy.parquet.crc
  contrib/format-deltalake/src/test/resources/data-reader-nested-struct/.part-00001-0f755735-3b5b-449a-8f93-92a40d9f065d-c000.snappy.parquet.crc
  contrib/format-deltalake/src/test/resources/data-reader-nested-struct/_delta_log/00000000000000000000.json
  contrib/format-deltalake/src/test/resources/data-reader-nested-struct/part-00000-f2547b28-9219-4628-8462-cc9c56edfebb-c000.snappy.parquet
  contrib/format-deltalake/src/test/resources/data-reader-nested-struct/part-00001-0f755735-3b5b-449a-8f93-92a40d9f065d-c000.snappy.parquet
  contrib/format-deltalake/src/test/resources/data-reader-partition-values/_delta_log/00000000000000000000.json
  contrib/format-deltalake/src/test/resources/data-reader-partition-values/as_int=0/as_long=0/as_byte=0/as_short=0/as_boolean=true/as_float=0.0/as_double=0.0/as_string=0/as_string_lit_null=null/as_date=2021-09-08/as_timestamp=2021-09-08 11%3A11%3A11/as_big_decimal=0/.part-00000-b9dc86ae-0134-4363-bd87-19cfb3403e9a.c000.snappy.parquet.crc
  contrib/format-deltalake/src/test/resources/data-reader-partition-values/as_int=0/as_long=0/as_byte=0/as_short=0/as_boolean=true/as_float=0.0/as_double=0.0/as_string=0/as_string_lit_null=null/as_date=2021-09-08/as_timestamp=2021-09-08 11%3A11%3A11/as_big_decimal=0/part-00000-b9dc86ae-0134-4363-bd87-19cfb3403e9a.c000.snappy.parquet
  contrib/format-deltalake/src/test/resources/data-reader-partition-values/as_int=1/as_long=1/as_byte=1/as_short=1/as_boolean=false/as_float=1.0/as_double=1.0/as_string=1/as_string_lit_null=null/as_date=2021-09-08/as_timestamp=2021-09-08 11%3A11%3A11/as_big_decimal=1/.part-00001-cb007d48-a9f5-40e7-adbe-60920680770f.c000.snappy.parquet.crc
  contrib/format-deltalake/src/test/resources/data-reader-partition-values/as_int=1/as_long=1/as_byte=1/as_short=1/as_boolean=false/as_float=1.0/as_double=1.0/as_string=1/as_string_lit_null=null/as_date=2021-09-08/as_timestamp=2021-09-08 11%3A11%3A11/as_big_decimal=1/part-00001-cb007d48-a9f5-40e7-adbe-60920680770f.c000.snappy.parquet
  contrib/format-deltalake/src/test/resources/data-reader-partition-values/as_int=__HIVE_DEFAULT_PARTITION__/as_long=__HIVE_DEFAULT_PARTITION__/as_byte=__HIVE_DEFAULT_PARTITION__/as_short=__HIVE_DEFAULT_PARTITION__/as_boolean=__HIVE_DEFAULT_PARTITION__/as_float=__HIVE_DEFAULT_PARTITION__/as_double=__HIVE_DEFAULT_PARTITION__/as_string=__HIVE_DEFAULT_PARTITION__/as_string_lit_null=__HIVE_DEFAULT_PARTITION__/as_date=__HIVE_DEFAULT_PARTITION__/as_timestamp=__HIVE_DEFAULT_PARTITION__/as_big_decimal=__HIVE_DEFAULT_PARTITION__/.part-00001-9ee474eb-385b-43cf-9acb-0fbed63e011c.c000.snappy.parquet.crc
  contrib/format-deltalake/src/test/resources/data-reader-partition-values/as_int=__HIVE_DEFAULT_PARTITION__/as_long=__HIVE_DEFAULT_PARTITION__/as_byte=__HIVE_DEFAULT_PARTITION__/as_short=__HIVE_DEFAULT_PARTITION__/as_boolean=__HIVE_DEFAULT_PARTITION__/as_float=__HIVE_DEFAULT_PARTITION__/as_double=__HIVE_DEFAULT_PARTITION__/as_string=__HIVE_DEFAULT_PARTITION__/as_string_lit_null=__HIVE_DEFAULT_PARTITION__/as_date=__HIVE_DEFAULT_PARTITION__/as_timestamp=__HIVE_DEFAULT_PARTITION__/as_big_decimal=__HIVE_DEFAULT_PARTITION__/part-00001-9ee474eb-385b-43cf-9acb-0fbed63e011c.c000.snappy.parquet
  contrib/format-deltalake/src/test/resources/data-reader-primitives/.part-00000-4f2f0b9f-50b3-4e7b-96a1-e2bb0f246b06-c000.snappy.parquet.crc
  contrib/format-deltalake/src/test/resources/data-reader-primitives/.part-00001-09e47b80-36c2-4475-a810-fbd8e7994971-c000.snappy.parquet.crc
  contrib/format-deltalake/src/test/resources/data-reader-primitives/_delta_log/00000000000000000000.json
  contrib/format-deltalake/src/test/resources/data-reader-primitives/part-00000-4f2f0b9f-50b3-4e7b-96a1-e2bb0f246b06-c000.snappy.parquet
  contrib/format-deltalake/src/test/resources/data-reader-primitives/part-00001-09e47b80-36c2-4475-a810-fbd8e7994971-c000.snappy.parquet
  contrib/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/StatisticsProvider.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillConstExecutor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetGroupScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetRowGroupScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetScanBatchCreator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/FilterEvaluatorUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetScanBatchCreator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/AbstractPluginImplementor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/PluginImplementor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginFilterRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginJoinRule.java
Labels: enhancement, new-format

#2710 DRILL-8360: Add Provided Schema for XML Reader
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfBatchReader.java
  contrib/format-xml/.gitignore
  contrib/format-xml/README.md
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/format-xml/src/test/resources/xml/simple_array.xml
  contrib/format-xml/src/test/resources/xml/simple_with_datatypes.xml
  contrib/storage-http/README.md
  contrib/storage-http/XML_Options.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXmlOptions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
  contrib/storage-http/src/test/resources/data/response.xml
Labels: enhancement, doc-impacting

#2712 DRILL-8363: upgrade postgresql to 42.4.3 due to security issue
  contrib/storage-jdbc/pom.xml
Labels: security, dependencies, backport-to-stable
