Repository apache/drill, pull requests merged in 2022-05, with the labels that each got.

#2527 DRILL-8035: Update Janino to 3.1.7 version
  exec/java-exec/src/main/java/org/apache/drill/exec/compile/ClassTransformer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/compile/JaninoClassCompiler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/compile/bytecode/ReplacingBasicValue.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/FunctionInitializer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/ImportGrabber.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/MethodGrabbingVisitor.java
  exec/jdbc-all/pom.xml
  pom.xml
Labels: Updates, dependencies

#2528 [MINOR UPDATE] Fix default auth mode in AuthMode.parseOrDefault
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePluginConfig.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStorageConfig.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestDataSource.java
  logical/src/main/java/org/apache/drill/common/logical/StoragePluginConfig.java
Labels: bug, Minor Update

#2526 DRILL-8204: Allow Provided Schema for HTTP Plugin in JSON Mode
  contrib/storage-http/JSON_Options.md
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpGroupScan.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpJsonOptions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpScanBatchCreator.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePlugin.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpSubScan.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestProvidedSchema.java
  contrib/storage-http/src/test/resources/data/schema_change_1.json
  contrib/storage-http/src/test/resources/data/schema_change_2.json
Labels: bug, enhancement

#2529 [MINOR UPDATE] Update AWS Java SDK to 1.12.211
  distribution/pom.xml
Labels: dependencies

#2530 DRILL-8207: Fix typo in JDBC config
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStorageConfig.java
Labels: bug, Minor Update

#2531 DRILL-8207: Fix Username Typo and password @JsonIgnore in JDBC SerDe
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStorageConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/CredentialProviderUtils.java
Labels: bug

#2532 DRILL-8208: Create builder for SqlSelect
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/SqlSelectBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/AnalyzeTableHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DescribeTableHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/MetastoreAnalyzeTableHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ShowSchemasHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ShowTablesHandler.java
Labels: calcite-update

#2540 DRILL-8215: Remove SecurityContext from PluginConfigWrapper
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/CredentialResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/StorageResources.java
  exec/java-exec/src/main/resources/rest/credentials/list.ftl
Labels: bug

#2536 DRILL-8212: Join queries fail with StackOverflowError
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdSelectivity.java
Labels: calcite-update

#2537 DRILL-8213: Replace deprecated RelNode.getRows with RelNode.estimateRowCount
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/cost/DrillRelMdRowCount.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/index/generators/IndexIntersectPlanGenerator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/RangePartitionExchangePrel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/RowKeyJoinPrel.java
Labels: calcite-update

#2534 DRILL-8210: Add substring convertlet
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillConvertletTable.java
Labels: calcite-update

#2542 DRILL-8219: Handle null catalog names returned by DB2 in storage-jdbc
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcCatalogSchema.java
Labels: bug, Minor Update, backport-to-stable

#2546 DRILL-8222: Fix wrong func impl of concat_delim, when null-value exist in middle args
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestVarArgFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/testing/VarCharConcatFunctions.java
Labels: bug, backport-to-stable

#2541 DRILL-8218: Add unit tests for StorageResource REST endpoints
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/StorageResourcesTest.java
  exec/java-exec/src/test/java/org/apache/drill/test/RestClientFixture.java
Labels: backport-to-stable

#2539 DRILL-8216: Use EVF-based JSON reader for Values operator
  contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveUtilities.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithH2.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithMySQL.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcWriterWithPostgres.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/config/Values.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/SchemaUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/values/ValuesBatchCreator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillValuesRelBase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillValuesRel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/ValuesPrel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/MetastoreAnalyzeTableHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/JsonStreamBatchReader.java
  exec/java-exec/src/test/java/org/apache/drill/TestProjectWithFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestValues.java
  logical/src/main/java/org/apache/drill/common/logical/data/Values.java
Labels: calcite-update

#2535 DRILL-8211: Replace deprecated RelNode.getChildExps with Project.getProjects
  contrib/format-maprdb/src/main/java/org/apache/drill/exec/store/mapr/db/MapRDBPushProjectIntoScan.java
  contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/plan/ElasticsearchProjectRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/common/DrillRelOptUtil.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillFilterItemStarReWriterRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillMergeProjectRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillProjectPushIntoLateralJoinRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushProjectIntoScanRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushRowKeyJoinToScanRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/PreProcessLogicalRel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/explain/NumberingRelWriter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/RewriteProjectToFlatten.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/visitor/SplitUpComplexExpressions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/ComplexUnnestVisitor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcRuleBase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/plan/rule/PluginProjectRule.java
Labels: calcite-update

#2538 DRILL-8214: Replace EnumerableTableScan usage with LogicalTableScan
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/FileSystemPartitionDescriptor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DirPrunedTableScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushProjectIntoScanRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillScanRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillTable.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/partition/PruneScanRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DrillTableInfo.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/table/function/WithOptionsTableMacro.java
Labels: calcite-update

#2548 DRILL-8224: Fix TestHttpPlugin#testSlowResponse
  .travis.yml
  contrib/storage-http/pom.xml
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
  exec/memory/base/src/main/java/org/apache/drill/exec/memory/AllocationManager.java
  exec/memory/base/src/main/java/org/apache/drill/exec/memory/BaseAllocator.java
Labels: CI

#2547 DRILL-8223: Refactor auth modes dropping DRILL_PROCESS and allowing credential providers everywhere
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraStorageConfig.java
  contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStorageConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePluginConfig.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestUserTranslationInHttpPlugin.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStorageConfig.java
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcStoragePlugin.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithH2IT.java
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoStoragePluginConfig.java
  contrib/storage-phoenix/src/main/java/org/apache/drill/exec/store/phoenix/PhoenixStoragePluginConfig.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/CredentialResources.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/OAuthRequests.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemConfig.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/TestClassicLocator.java
  logical/src/main/java/org/apache/drill/common/logical/CredentialedStoragePluginConfig.java
  logical/src/main/java/org/apache/drill/common/logical/StoragePluginConfig.java
Labels: bug

#2549 DRILL-8225: Update LogParser and Yauaa to support User-Agent Client Hints
  contrib/format-excel/pom.xml
  contrib/format-httpd/pom.xml
  contrib/udfs/README.md
  contrib/udfs/pom.xml
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/UserAgentAnalyzerProvider.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/UserAgentFunctions.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestUserAgentFunctions.java
  pom.xml
Labels: enhancement, doc-impacting

#2551 DRILL-8227: JConnect and jTDS JDBC drivers do not implement Connection::getSchema
  contrib/storage-jdbc/pom.xml
  contrib/storage-jdbc/src/main/java/org/apache/drill/exec/store/jdbc/JdbcCatalogSchema.java
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
  contrib/storage-jdbc/src/test/resources/mssql-test-data.ms.sql
Labels: bug, backport-to-stable

#2533 DRILL-8209: Introduce rule for converting join with distinct input to semi-join
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/RuleInstance.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillDistinctJoinToSemiJoinRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillSemiJoinRel.java
Labels: calcite-update

#2554 DRILL-8228: GetColumnsMetadataWhenNoRowsTest regression
  exec/jdbc/src/test/java/org/apache/drill/jdbc/test/Drill2288GetColumnsMetadataWhenNoRowsTest.java
Labels: backport-to-stable

#2553 DRILL-8229: Add Parameter to Skip Malformed Records to HTTP UDF
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
Labels: bug, minor-update

#2556 [MINOR UPDATE] Disable TestJdbcPluginWithMSSQL when not on amd64.
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
Labels: ci, backport-to-stable

#2557 [MINOR UPDATE] Disable TestJdbcPluginWithMSSQL when not on amd64.
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
Labels: ci, backport-to-stable

#2559 DRILL-8223: Change JDK 17 Docker base image from Oracle Linux to Debian.
  hooks/build
Labels: backport-to-stable

#2564 DRILL-8237: Limit is not pushed down to scan for MSSQL
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/enumerable/plan/DrillJdbcSort.java
Labels: bug

#2558 DRILL-8232: Add support for user credentials to VaultCredentialsProvider
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestUserTranslationInHttpPlugin.java
  docs/dev/PluginCredentialsProvider.md
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/PluginConfigWrapper.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/EnvCredentialsProvider.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/UsernamePasswordCredentials.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/UsernamePasswordWithProxyCredentials.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/oauth/OAuthTokenCredentials.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/security/vault/VaultCredentialsProvider.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestVaultUserAuthenticator.java
  exec/java-exec/src/test/java/org/apache/drill/storage/CredentialsProviderImplementationsTest.java
  exec/java-exec/src/test/java/org/apache/drill/storage/CredentialsProviderSerDeTest.java
  exec/java-exec/src/test/resources/vault/read-vault-secrets.hcl
  logical/src/main/java/org/apache/drill/common/logical/security/CredentialsProvider.java
  logical/src/main/java/org/apache/drill/common/logical/security/PlainCredentialsProvider.java
Labels: security, breaking

#2483 DRILL-8149: large xlsx configs
  contrib/format-excel/README.md
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelFormatConfig.java
Labels: updates, performance
