Repository apache/drill, pull requests merged in 2022-06, with the labels that each got.

#2565 DRILL-8113: Support building with a JDK 8 target using newer JDKs
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/SpnegoConfig.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitBitKerberos.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberos.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/user/security/TestUserBitKerberosEncryption.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestDrillSpnegoAuthenticator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoAuthentication.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestSpnegoConfig.java
  pom.xml
Labels: backport-to-stable

#2568 DRILL-8242: Fix output for HttpHelperFunctions
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/DrillComplexWriterFuncHolder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ops/BufferManagerImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectBatchBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectMemoryManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectRecordBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectionMaterializer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/Projector.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectorTemplate.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ColumnBuilder.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ResultSetLoaderImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/record/AbstractRecordBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/record/BatchSchema.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/vector/complex/impl/VectorContainerWriter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/spnego/TestDrillSpnegoAuthenticator.java
  exec/vector/src/main/java/org/apache/drill/exec/vector/complex/impl/ComplexWriterImpl.java
Labels: bug, json

#2571 DRILL-8244: HTTP_Request Not Passing Down Config Variables
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpUdfUtils.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
Labels: bug, json

#2464 DRILL-8132: Improvement of RPC
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/control/ControlClient.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/control/ControlServer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/data/DataClient.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/data/DataServer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/BootStrapContext.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/DrillbitContext.java
  exec/java-exec/src/main/resources/drill-module.conf
Labels: performance

#2572 DRILL-8245: Project pushdown depends on rules order and might not happen
  contrib/format-httpd/src/main/java/org/apache/drill/exec/store/httpd/HttpdParser.java
  contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReader.java
  contrib/format-httpd/src/test/java/org/apache/drill/exec/store/httpd/TestHTTPDLogReaderUserAgent.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/PlannerPhase.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillPushFilterPastProjectRule.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillScanRel.java
Labels: performance, calcite-update

#2573 DRILL-8248: Fix http_request for several rows
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpHelperFunctions.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/udfs/HttpUdfUtils.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
  contrib/storage-http/src/test/resources/data/p4.json
  contrib/storage-kafka/src/main/java/org/apache/drill/exec/store/kafka/decoders/JsonMessageReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectRecordBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/resultSet/impl/ResultSetLoaderImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/JsonLoaderImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/loader/SingleElementIterator.java
Labels: bug, udf

#2569 DRILL-8199: Convert Excel EVF1 to EVF2
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelFormatConfig.java
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelFormatPlugin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/scan/v3/schema/DynamicSchemaFilter.java
Labels: refactoring

#2575 [MINOR UPDATE] Fix Port Clash Issue in HTTP Plugin Tests
  common/src/main/java/org/apache/drill/common/util/DrillFileUtils.java
  contrib/native/client/src/include/drill/recordBatch.hpp
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestProvidedSchema.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestUserTranslationInHttpPlugin.java
Labels: bug, minor-update

#2577 DRILL-8251: Upgrade Hadoop 2 Due to CVE
  pom.xml
Labels: security, dependencies
