Repository apache/drill, pull requests merged in 2023-02, with the labels that each got.

#2739 DRILL-8387: Add Support for User Translation to ElasticSearch Plugin
  contrib/storage-elasticsearch/.gitignore
  contrib/storage-elasticsearch/README.md
  contrib/storage-elasticsearch/pom.xml
  contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStorageConfig.java
  contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStoragePlugin.java
  contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/schema/ElasticsearchDrillSchemaFactory.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticComplexTypesTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticInfoSchemaTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchPlanTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchQueryTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchUserTranslationTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/TestElasticsearchSuite.java
Labels: enhancement, doc-impacting, minor-update, security

#2636 DRILL-8290: Early exit from recursive file listing for LIMIT 0 queries
  .editorconfig
  common/src/main/java/org/apache/drill/common/exceptions/UserException.java
  exec/java-exec/src/main/java/org/apache/calcite/jdbc/DynamicRootSchema.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/SelectionBasedTableScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/handlers/DefaultSqlHandler.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/parser/FindLimit0SqlVisitor.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSelection.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/WorkspaceSchemaFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/compression/DrillCompressionCodecFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/metadata/MetadataPathUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/util/DrillFileSystemUtil.java
  exec/java-exec/src/main/java/org/apache/drill/exec/util/FileSystemUtil.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/test/java/org/apache/drill/PlanTestBase.java
  exec/java-exec/src/test/java/org/apache/drill/TestDirScanToValuesConversion.java
  exec/java-exec/src/test/java/org/apache/drill/TestSelectWithOption.java
  exec/java-exec/src/test/java/org/apache/drill/TestUnionAll.java
  exec/java-exec/src/test/java/org/apache/drill/TestUnionDistinct.java
  exec/java-exec/src/test/java/org/apache/drill/exec/TestEmptyInputSql.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestJoinEmptyDirTable.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetGroupScan.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetMetadataCache.java
  exec/java-exec/src/test/java/org/apache/drill/test/BaseTestQuery.java
Labels: performance

#2728 DRILL-8372: Unfreed buffers when running a LIMIT 0 query over delimited text
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/limit/LimitRecordBatch.java
  exec/java-exec/src/test/java/org/apache/drill/TestBugFixes.java
Labels: bug

#2749 DRILL-8379: Update Calcite to 1.33.0
  exec/java-exec/src/main/codegen/data/DateIntervalFunc.tdd
  exec/java-exec/src/main/codegen/data/Parser.tdd
  exec/java-exec/src/main/codegen/templates/DateIntervalFunctionTemplates/TimestampDiffFunction.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillOptiq.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/logical/DrillRelFactories.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/PrelFactories.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/DrillConvertletTable.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/TypeInferenceUtils.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestTimestampAddDiffFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestAnalyze.java
  exec/jdbc-all/pom.xml
  pom.xml
Labels: calcite-update

#2748 DRILL-8395: Add Support for Insert and Drop Table to GoogleSheets Plugin
  contrib/storage-googlesheets/README.md
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchInsertWriter.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchWriter.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsInsertWriter.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsInsertWriterBatchCreator.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsStoragePlugin.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsDrillSchema.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/schema/GoogleSheetsRootSchema.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsUtils.java
  contrib/storage-googlesheets/src/test/java/org/apache/drill/exec/store/googlesheets/TestGoogleSheetsWriter.java
  contrib/storage-googlesheets/src/test/resources/data/insert_data.csvh
  contrib/storage-googlesheets/src/test/resources/data/insert_data2.csvh
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/SchemaUtilities.java
Labels: enhancement, doc-impacting

#2751 DRILL-8396: Update checkstyle version
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetReaderUtility.java
  pom.xml
Labels: dependencies

#2750 DRILL-8309: Upgrade slf4j to 2.0.x
  contrib/storage-hive/hive-exec-shade/pom.xml
  exec/java-exec/pom.xml
  exec/jdbc/pom.xml
  pom.xml
Labels: dependencies

#2755 DRILL-8399: MS Access Reader Misinterprets Data Types
  contrib/format-access/src/main/java/org/apache/drill/exec/store/msaccess/MSAccessBatchReader.java
  contrib/format-access/src/test/java/org/apache/drill/exec/store/msaccess/TestMSAccessReader.java
Labels: bug, minor-update

#2757 DRILL-8401: Skip nested MAP column without children when creating parquet tables
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
Labels: bug

#2756 DRILL-8117: Upgrade unit tests to the cluster fixture framework
  .github/workflows/ci.yml
  common/pom.xml
  common/src/main/java/org/apache/drill/common/PlanStringBuilder.java
  common/src/main/java/org/apache/drill/common/config/DrillConfig.java
  common/src/main/java/org/apache/drill/common/util/DrillStringUtils.java
  common/src/test/java/org/apache/drill/common/util/function/TestCheckedFunction.java
  common/src/test/java/org/apache/drill/test/DrillTest.java
  common/src/test/java/org/apache/drill/test/UserExceptionMatcher.java
  contrib/format-log/src/test/java/org/apache/drill/exec/store/log/TestLogReaderIssue.java
  contrib/storage-hive/core/src/test/java/org/apache/drill/exec/TestHiveDrillNativeParquetReader.java
  contrib/storage-hive/core/src/test/java/org/apache/drill/exec/impersonation/hive/BaseTestHiveImpersonation.java
  contrib/storage-hive/core/src/test/java/org/apache/drill/exec/impersonation/hive/TestSqlStdBasedAuthorization.java
  contrib/storage-hive/core/src/test/java/org/apache/drill/exec/impersonation/hive/TestStorageBasedHiveAuthorization.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkWriterTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/TestWindowFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/client/DrillClientStateTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/BaseTestImpersonation.java
  exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/TestImpersonationDisabledWithMiniDFS.java
  exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/TestImpersonationMetadata.java
  exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/TestImpersonationQueries.java
  exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/TestInboundImpersonation.java
  exec/java-exec/src/test/java/org/apache/drill/exec/planner/sql/CrossJoinTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/TestOptions.java
  exec/java-exec/src/test/java/org/apache/drill/test/ClientFixture.java
  exec/java-exec/src/test/java/org/apache/drill/test/ClusterFixture.java
  exec/java-exec/src/test/java/org/apache/drill/test/QueryBuilder.java
  pom.xml
Labels: code-cleanup

#2764 [MINOR UPDATE] Add Email Templates to ASF.yml
  .asf.yaml
Labels: minor-update

#2762 DRILL-8402: Add REGEXP_EXTRACT Function
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/CharSequenceWrapper.java
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/StringFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/expr/fn/impl/TestRegexpFunctions.java
Labels: enhancement, minor-update, udf

#2766 DRILL-8158: Fix 2 Reproducible Builds issues Remaining After DRILL-8158
  pom.xml
Labels: code-cleanup, minor-update, backport-to-stable

#2768 DRILL-8406: Enable implicit casting of VARCHAR and BIT args in aggregate functions
  docs/dev/Release.md
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/AggregateErrorFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/TestImplicitCasting.java
Labels: backport-to-stable
