Repository apache/drill, pull requests merged in 2023-08, with the labels that each got.

#2747 DRILL-8393: Allow parameters to be passed to headers through SQL in WHERE clause
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpStoragePluginConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFFunctions.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpUDFWithAliases.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthProcess.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestOAuthTokenUpdate.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestProvidedSchema.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestUserTranslationInHttpPlugin.java
Labels: enhancement, doc-impacting, breaking

#2822 [MINOR UPDATE]: Fix Hadoop 3 impersonation test errors during CI runs
  exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/BaseTestImpersonation.java
  exec/java-exec/src/test/java/org/apache/drill/exec/impersonation/TestInboundImpersonation.java
Labels: bug, ci, backport-to-stable

#2819 DRILL-8450: Add Data Type Inference to XML Format Plugin
  common/src/main/java/org/apache/drill/common/Typifier.java
  contrib/format-xml/README.md
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLBatchReader.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLFormatConfig.java
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/storage-http/XML_Options.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXMLBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpXmlOptions.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
Labels: enhancement, doc-impacting

#2823 DRILL-8452: Library upgrades
  contrib/storage-elasticsearch/pom.xml
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/TestElasticsearchSuite.java
  contrib/storage-hive/core/pom.xml
  contrib/storage-kafka/pom.xml
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaFilterPushdownTest.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaMessageGenerator.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaQueriesTest.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/KafkaTestBase.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/MessageIteratorTest.java
  contrib/storage-kafka/src/test/java/org/apache/drill/exec/store/kafka/TestKafkaSuite.java
  contrib/storage-kafka/src/test/resources/login.jaasconf
  distribution/docker-compose/Dockerfile
  distribution/docker-compose/README.txt
  distribution/docker-compose/docker-compose.yml
  distribution/docker-compose/drill-override.conf
  distribution/docker-compose/logback.xml
  distribution/src/assemble/component.xml
  drill-yarn/src/main/java/org/apache/drill/yarn/core/ClusterDef.java
  exec/java-exec/pom.xml
  exec/java-exec/src/main/codegen/templates/Parser.jj
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/FunctionInitializer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/auth/DrillSpnegoLoginService.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/ssl/SslContextFactoryConfigurator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/ZookeeperTestUtil.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/unit/TestOutputBatchSize.java
  exec/java-exec/src/test/java/org/apache/drill/exec/server/rest/ssl/SslContextFactoryConfiguratorTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/sql/TestInfoSchema.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/json/TestJsonReader.java
  exec/java-exec/src/test/resources/login.jaasconf
  exec/java-exec/src/test/resources/vault/read-vault-secrets.hcl
  exec/jdbc-all/pom.xml
  exec/jdbc/pom.xml
  exec/vector/src/main/codegen/templates/RepeatedValueVectors.java
  pom.xml
Labels: dependencies, backport-to-stable

#2821 DRILL-8436: Upgrade Hadoop 3.2.4 → 3.3.6
  contrib/storage-hive/core/pom.xml
  contrib/storage-phoenix/pom.xml
  exec/java-exec/pom.xml
  exec/jdbc-all/pom.xml
  exec/jdbc-all/src/main/resources/core-site.xml
  exec/jdbc-all/src/test/java/org/apache/drill/jdbc/ITTestShadedJar.java
  exec/jdbc-all/src/test/resources/core-site.xml
  pom.xml
Labels: dependencies
