Repository apache/drill, pull requests merged in 2023-11, with the labels that each got.

#2845 DRILL-8461: Prevent XXE Attacks in XML Format Plugin
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/format-xml/src/test/resources/xml/bad.xml
Labels: bug, security, backport-to-stable

#2843 DRILL-8446: Incorrect use of OperatingSystemMXBean
  common/src/main/java/org/apache/drill/exec/metrics/CpuGaugeSet.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/TestSplunkUserTranslation.java
Labels: bug, backport-to-stable

#2850 DRILL-8464. Upgrade to checkout action v4
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish-snapshot.yml
Labels: minor-update, dependencies, backport-to-stable

#2849 DRILL-8463. Bouncy Castle 1.77
  exec/java-exec/pom.xml
  exec/jdbc-all/pom.xml
  pom.xml
Labels: minor-update, dependencies, backport-to-stable
