Repository apache/drill, pull requests merged in 2023-04, with the labels that each got.

#2782 [MINOR-UPDATE]: Drop conjars repo and revert ci.yml runner image to ubuntu-latest
  .github/workflows/ci.yml
  contrib/storage-splunk/pom.xml
  distribution/src/main/resources/drill-override-example.conf
  exec/java-exec/src/test/resources/drill-udf/pom.xml
  pom.xml
Labels: minor-update, backport-to-stable

#2784 DRILL-8416: Memory leak when the async Parquet reader skips empty pages
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/AsyncPageReader.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestEmptyParquet.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet2/TestDrillParquetReader.java
  exec/java-exec/src/test/resources/parquet/empty_dict_pages.parquet
Labels: bug, backport-to-stable, regression

#2794 DRILL-8424: Accommodate RexBuilder changes made for SAFE_CAST
  .gitignore
  .mvn/extensions.xml
  distribution/pom.xml
  exec/java-exec/src/main/codegen/templates/Parser.jj
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/sql/conversion/DrillRexBuilder.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestCastFunctions.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestNewDateFunctions.java
  pom.xml
Labels: doc-impacting, dependencies, calcite-update

#2783 DRILL-8417: Allow Excel Reader to Ignore Formula Errors
  contrib/format-excel/README.md
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelBatchReader.java
  contrib/format-excel/src/main/java/org/apache/drill/exec/store/excel/ExcelFormatConfig.java
  contrib/format-excel/src/test/java/org/apache/drill/exec/store/excel/TestExcelFormat.java
  contrib/format-excel/src/test/resources/excel/text-formula.xlsx
Labels: enhancement, doc-impacting, minor-update

#2793 DRILL-8421: Parquet microsecond columns
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetTableMetadataUtils.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/NullableFixedByteAlignedReaders.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetFixedWidthDictionaryReaders.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/metadata/FileMetadataCollector.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestMicrosecondColumns.java
  exec/java-exec/src/test/resources/parquet/microseconds.parquet
Labels: bug, backport-to-stable
