Repository apache/drill, pull requests merged in 2023-10, with the labels that each got.

#2833 DRILL-8456: upgrade poi and commons-compress
  contrib/format-excel/pom.xml
  pom.xml
Labels: updates, minor-update, dependencies

#2825 DRILL-8454: Disable unsupported MapR profile and plugin
  common/src/main/java/org/apache/drill/common/config/DrillProperties.java
  contrib/pom.xml
  contrib/storage-hbase/pom.xml
  contrib/storage-hive/core/pom.xml
  contrib/storage-hive/core/src/main/java/org/apache/drill/exec/store/hive/HiveStoragePlugin.java
  distribution/pom.xml
  distribution/src/assemble/component.xml
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfigClient.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLConfigServer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/ssl/SSLCredentialsProvider.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/srcMapr/main/java/org/apache/drill/exec/ssl/SSLCredentialsProviderMaprClient.java
  exec/java-exec/srcMapr/main/java/org/apache/drill/exec/ssl/SSLCredentialsProviderMaprServer.java
  exec/jdbc-all/pom.xml
  exec/jdbc/pom.xml
  metastore/iceberg-metastore/pom.xml
  pom.xml
Labels: code-cleanup

#2839 [MINOR UPDATE]: Improve the Github CI memory constraint workarounds
  .github/workflows/ci.yml
  pom.xml
Labels: minor-update, ci, backport-to-stable

#2841 [DRILL-8459]: Bump Avro to 1.11.3
  pom.xml
Labels: minor-update, security, dependencies, backport-to-stable

#2838 DRILL-8458: Use correct size of definition level bytes slice when reading Parquet v2 data page
  exec/java-exec/src/main/java/org/apache/parquet/hadoop/ColumnChunkIncReadStore.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/ParquetSimpleTestFileGenerator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestParquetComplex.java
  exec/java-exec/src/test/resources/parquet/parquet_v2_repeated_int.parquet
Labels: bug, backport-to-stable

#2840 [DRILL-8457] Allow configuring csv parser in http storage plugin configuration
  contrib/storage-http/CSV_Options.md
  contrib/storage-http/README.md
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpApiConfig.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpCSVOptions.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpApiConfig.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpCSVOptions.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestHttpPlugin.java
  contrib/storage-http/src/test/resources/data/csvOptions.json
  contrib/storage-http/src/test/resources/data/exampleHttpApiConfig.json
  contrib/storage-http/src/test/resources/data/response.tsv
Labels: enhancement, doc-impacting
