Repository apache/drill, pull requests merged in 2023-05, with the labels that each got.

#2795 DRILL-8385: Add support for disabling SSL certificate verification in the Elasticsearch plugin
  contrib/storage-elasticsearch/README.md
  contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStorageConfig.java
  contrib/storage-elasticsearch/src/main/resources/bootstrap-storage-plugins.json
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticComplexTypesTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticInfoSchemaTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchPlanTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchQueryTest.java
  contrib/storage-elasticsearch/src/test/java/org/apache/drill/exec/store/elasticsearch/ElasticSearchUserTranslationTest.java
Labels: doc-impacting, minor-update

#2797 DRILL-8428: ElasticSearch Config Missing Getters
  contrib/storage-elasticsearch/src/main/java/org/apache/drill/exec/store/elasticsearch/ElasticsearchStorageConfig.java
Labels: bug, minor-update, backport-to-stable

#2801 DRILL-8433: Add Percent Change UDF to Drill
  contrib/udfs/README.md
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DistributionFunctions.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDistributionFunctions.java
Labels: enhancement, doc-impacting, minor-update, udf

#2805 DRILL-8158: Remove non-reproducible entry
  pom.xml
Labels: code-cleanup, minor-update
