Repository apache/drill, pull requests merged in 2023-03, with the labels that each got.

#2767 DRILL-8405: Upgrade to snakeyaml 2.0 due to CVE
  metastore/rdbms-metastore/pom.xml
  pom.xml
Labels: minor-update, security, dependencies, backport-to-stable

#2769 [MINOR UPDATE]: Fix Code Gen Error in Nearest Date UDF
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DateFunctions.java
Labels: bug, minor-update, backport-to-stable

#2770 DRILL-8407: Add Support for SFTP File Systems
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/FileSystemPlugin.java
Labels: enhancement, minor-update

#2774 DRILL-8411: GoogleSheets Reader Will Not Read More than 1K Rows
  common/src/main/java/org/apache/drill/common/Typifier.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/GoogleSheetsBatchReader.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/columns/GoogleSheetsColumnWriter.java
  contrib/storage-googlesheets/src/main/java/org/apache/drill/exec/store/googlesheets/utils/GoogleSheetsRangeBuilder.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java
Labels: bug, minor-update, backport-to-stable

#2778 DRILL-8413: Add DNS Lookup Functions
  contrib/udfs/README.md
  contrib/udfs/pom.xml
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DNSFunctions.java
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DNSUtils.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDNSFunctions.java
  pom.xml
Labels: enhancement, doc-impacting

#2779 DRILL-8414: Index Paginator Not Working When Provided URL
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/HttpBatchReader.java
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/IndexPaginator.java
  contrib/storage-http/src/test/java/org/apache/drill/exec/store/http/TestPagination.java
  contrib/storage-http/src/test/resources/data/index_response10.json
  contrib/storage-http/src/test/resources/data/index_response11.json
  contrib/storage-http/src/test/resources/data/index_response12.json
  contrib/storage-http/src/test/resources/data/index_response5.json
  contrib/storage-http/src/test/resources/data/index_response6.json
  contrib/storage-http/src/test/resources/data/index_response7.json
  contrib/storage-http/src/test/resources/data/index_response8.json
  contrib/storage-http/src/test/resources/data/index_response9.json
Labels: bug, backport-to-stable

#2777 DRILL-8409: Support the configuration of bind addresses for network services
  exec/java-exec/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/control/ControllerImpl.java
  exec/java-exec/src/main/java/org/apache/drill/exec/rpc/data/DataConnectionCreator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/rest/WebServer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/service/ServiceEngine.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetRecordReader.java
  exec/java-exec/src/main/java/org/apache/parquet/hadoop/ParquetColumnChunkPageWriteStore.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitBitKerberos.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitRpc.java
  exec/rpc/src/main/java/org/apache/drill/exec/rpc/BasicServer.java
Labels: bug, backport-to-stable
