Repository apache/drill, pull requests merged in 2023-01, with the labels that each got.

#2734 DRILL-8381: Add support for filtered aggregate calls
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/AggPrelBase.java
  exec/java-exec/src/test/java/org/apache/drill/exec/fn/impl/TestAggregateFunctions.java
Labels: enhancement

#2729 DRILL-8376: Add Distribution UDFs
  contrib/udfs/README.md
  contrib/udfs/src/main/java/org/apache/drill/exec/udfs/DistributionFunctions.java
  contrib/udfs/src/test/java/org/apache/drill/exec/udfs/TestDistributionFunctions.java
  contrib/udfs/src/test/resources/regr_test.csvh
  contrib/udfs/src/test/resources/test_data.csvh
Labels: enhancement, doc-impacting, minor-update, udf

#2738 DRILL-8386: Add Support for User Translation for Cassandra
  contrib/storage-cassandra/README.md
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraStorageConfig.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/CassandraStoragePlugin.java
  contrib/storage-cassandra/src/main/java/org/apache/drill/exec/store/cassandra/schema/CassandraRootDrillSchemaFactory.java
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/BaseCassandraTest.java
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/CassandraUserTranslationTest.java
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/TestCassandraSuite.java
  contrib/storage-splunk/README.md
Labels: enhancement, doc-impacting, minor-update

#2737 DRILL-8384: Add Format Plugin for Microsoft Access
  contrib/format-access/README.md
  contrib/format-access/pom.xml
  contrib/format-access/src/main/java/org/apache/drill/exec/store/msaccess/MSAccessBatchReader.java
  contrib/format-access/src/main/java/org/apache/drill/exec/store/msaccess/MSAccessFormatConfig.java
  contrib/format-access/src/main/java/org/apache/drill/exec/store/msaccess/MSAccessFormatPlugin.java
  contrib/format-access/src/main/resources/bootstrap-format-plugins.json
  contrib/format-access/src/main/resources/drill-module.conf
  contrib/format-access/src/test/java/org/apache/drill/exec/store/msaccess/TestMSAccessReader.java
  contrib/format-access/src/test/resources/data/V1997/testV1997.mdb
  contrib/format-access/src/test/resources/data/V2000/testV2000.mdb
  contrib/format-access/src/test/resources/data/V2003/testV2003.mdb
  contrib/format-access/src/test/resources/data/V2007/testV2007.accdb
  contrib/format-access/src/test/resources/data/V2010/testV2010.accdb
  contrib/format-access/src/test/resources/data/V2019/extDateTestV2019.accdb
  contrib/format-access/src/test/resources/data/adox_jet4.mdb
  contrib/pom.xml
  distribution/pom.xml
  distribution/src/assemble/component.xml
  pom.xml
Labels: enhancement, new-format, doc-impacting

#2740 [MINOR UPDATE]: Clear Results after Splunk Unit Tests
  contrib/storage-cassandra/src/test/java/org/apache/drill/exec/store/cassandra/CassandraUserTranslationTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/TestSplunkUserTranslation.java
Labels: code-cleanup, minor-update

#2741 [MINOR UPDATE]: Remove travis.yml
  .travis.yml
Labels: minor-update, ci

#2742 DRILL-8390: Minor Improvements to PDF Reader
  contrib/format-pdf/README.md
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfBatchReader.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfMetadataReader.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfRowIterator.java
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfUtils.java
  contrib/format-pdf/src/test/java/org/apache/drill/exec/store/pdf/TestPdfFormat.java
Labels: bug, doc-impacting, minor-update

#2743 DRILL-8391: Disable auto complete on the password field of web UI login forms
  drill-yarn/src/main/resources/drill-am/login.ftl
  exec/java-exec/src/main/resources/rest/login.ftl
Labels: security, ui, backport-to-stable

#2744 DRILL-8392: Empty Tables Causes Index Out of Bounds Exception on PDF Reader
  contrib/format-pdf/src/main/java/org/apache/drill/exec/store/pdf/PdfBatchReader.java
Labels: bug, minor-update
