Repository apache/drill, pull requests merged in 2024-10, with the labels that each got.

#2948 [MINOR UPDATE]: Upgrade the MSSQL test container for compatibility with Linux 6.7.
  contrib/storage-jdbc/src/test/java/org/apache/drill/exec/store/jdbc/TestJdbcPluginWithMSSQL.java
  pom.xml
Labels: code-cleanup, minor-update, ci

#2954 [MINOR UPDATE] Upgrade jetty to 9.4.56.v20240826 due to CVE-2024-8184
  pom.xml
Labels: minor-update, security, dependencies

#2952 DRILL-8513: Right Hash Join with empty Left table ruturns 0 result
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/HashJoinProbeTemplate.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/join/TestHashJoin.java
  exec/java-exec/src/test/resources/join/hj_right_outer_empty_left_input.json
Labels: bug

#2955 [MINOR UPDATE] use same version of commons-io in all drill projects
  tools/fmpp/pom.xml
Labels: dependencies
