Repository apache/drill, pull requests merged in 2024-04, with the labels that each got.

#2898 DRILL-8486: ParquetDecodingException: could not read bytes at offset
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenEntryDictionaryReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenEntryReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenNullableDictionaryReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/VarLenNullableEntryReader.java
Labels: bug, minor-update, backport-to-stable

#2905 [MINOR UPDATE] replace deprecate method use in jackson
  logical/src/main/java/org/apache/drill/common/util/AbstractDynamicBean.java
Labels: code-cleanup, minor-update, dependencies

#2904 [MINOR UPDATE] update to netty 4.1.109 due to CVE-2024-29025
  exec/memory/base/src/main/java/io/netty/buffer/PooledByteBufAllocatorL.java
  pom.xml
Labels: minor-update, security, dependencies, backport-to-stable

#2908 DRILL-8493: Drill Unable to Read XML Files with Namespaces
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/format-xml/src/test/resources/xml/sitemap.xml
Labels: bug, backport-to-stable, verified
