Repository apache/drill, pull requests merged in 2024-01, with the labels that each got.

#2863 DRILL-8420: Clean up some cruft related to the removed shaded Guava
  docs/dev/UpgradeGuava.md
  drill-shaded/pom.xml
  exec/jdbc-all/pom.xml
Labels: code-cleanup

#2859 DRILL-8468: Drill doesn't perform drill.exec.storage.action_on_plugins_override_file action
  exec/java-exec/src/main/java/org/apache/drill/exec/store/StoragePluginRegistryImpl.java
Labels: bug, backport-to-stable

#2864 DRILL-8445: Upgrade Janino 3.1.8 → 3.1.11
  distribution/src/assemble/component.xml
  pom.xml
Labels: dependencies, backport-to-stable

#2865 DRILL-8460: Upgrade ZooKeeper 3.5.7 → 3.5.10 and Curator 5.2.0 → 5.5.0
  exec/jdbc-all/pom.xml
  pom.xml
Labels: dependencies, backport-to-stable

#2862 DRILL-8470: Bump MongoDB Driver to Latest Version
  contrib/format-deltalake/pom.xml
  contrib/format-image/pom.xml
  contrib/format-image/src/test/resources/image/jpeg.json
  pom.xml
Labels: minor-update, dependencies, backport-to-stable

#2868 [MINOR UPDATE]: Update the copyright year in NOTICE
  NOTICE
  distribution/src/main/resources/NOTICE
Labels: backport-to-stable

#2515 DRILL-8188: Convert HDF5 format to EVF2
  contrib/format-hdf5/pom.xml
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5BatchReader.java
  contrib/format-hdf5/src/main/java/org/apache/drill/exec/store/hdf5/HDF5FormatPlugin.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/TestScanOuputSchema.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/scan/v3/lifecycle/TestOutputBatchBuilder.java
  exec/java-exec/src/test/java/org/apache/drill/test/rowSet/RowSetUtilities.java
  exec/vector/src/main/java/org/apache/drill/exec/vector/accessor/writer/UnionVectorShim.java
Labels: refactoring, dependencies

#2872 [MINOR UPDATE]: Enable master branch protection
  .asf.yaml
  docs/dev/Release.md
Labels: minor-update, security

#2875 DRILL-8478. HashPartition memory leak when it allocate memory exception with OutOfMemoryException (#2874)
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/common/HashPartition.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/AbstractHashBinaryRecordBatch.java
Labels: bug, backport-to-stable
