Repository apache/drill, pull requests merged in 2024-05, with the labels that each got.

#2901 DRILL-8489: Sender memory leak when rpc encode exception
  exec/rpc/src/main/java/org/apache/drill/exec/rpc/RpcEncoder.java
Labels: bug, minor-update, backport-to-stable, stability, verified

#2900 DRILL-8488: HashJoinPOP memory leak is caused by OutOfMemoryException
  exec/java-exec/src/main/java/org/apache/drill/exec/cache/VectorAccessibleSerializable.java
Labels: bug, minor-update

#2912 DRILL-8495: HTTP Caching Not Saving Pages
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/util/SimpleHttp.java
Labels: bug, backport-to-stable, regression

#2897 DRILL-8480: Cleanup before finished. 0 out of 1 streams have finished
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/NestedLoopJoin.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/NestedLoopJoinBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/NestedLoopJoinTemplate.java
Labels: bug
