Repository apache/drill, pull requests merged in 2024-08, with the labels that each got.

#2932 DRILL-8505: Fix Docker Hub automated container image builds
  Dockerfile
  hooks/build
Labels: ci, backport-to-stable

#2933 [MINOR UPDATE] Update Docker-Compose Docs
  contrib/storage-druid/README.md
  contrib/storage-druid/src/test/resources/druid/docker-compose.yaml
  distribution/docker-compose/README.txt
  distribution/docker-compose/docker-compose.yml
Labels: documentation, minor-update

#2935 DRILL-8506: Ignore JSON Elements with Empty Keys
  exec/java-exec/src/main/java/org/apache/drill/exec/store/easy/json/parser/ObjectParser.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/easy/json/loader/TestBasics.java
Labels: minor-update, backport-to-stable
