Repository apache/drill, pull requests merged in 2024-03, with the labels that each got.

#2885 DRILL-8482:Assign region throw exception when some region is deployed…
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseGroupScan.java
  contrib/storage-hbase/src/test/java/org/apache/drill/hbase/TestHBaseRegionScanAssignments.java
Labels: bug, backport-to-stable

#2884 DRILL-8141: Ability to query XML root attributes
  contrib/format-xml/src/main/java/org/apache/drill/exec/store/xml/XMLReader.java
  contrib/format-xml/src/test/java/org/apache/drill/exec/store/xml/TestXMLReader.java
  contrib/format-xml/src/test/resources/xml/no_nest.xml
Labels: bug, minor-update, backport-to-stable

#2878 DRILL-8479: Merge Join Leak When Depleting Incoming Batches Throw Exception
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/MergeJoinBatch.java
Labels: bug, backport-to-stable

#2891 DRILL-8485: HashJoinPOP memory leak is caused by an oom exception whe…
  exec/java-exec/src/main/java/org/apache/drill/exec/cache/VectorAccessibleSerializable.java
Labels: bug, backport-to-stable

#2894 [MINOR UPDATE] upgrade actions
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/publish-snapshot.yml
Labels: minor-update, ci, backport-to-stable

#2892 [MINOR UPDATE] update commons-compress due to CVEs
  contrib/format-excel/pom.xml
  pom.xml
Labels: security, dependencies

#2889 DRILL-8484: HashJoinPOP memory leak is caused by an oom exception wh…
  exec/java-exec/src/main/java/org/apache/drill/exec/cache/VectorAccessibleSerializable.java
Labels: bug, minor-update, backport-to-stable

#2888 DRILL-8483: SpilledRecordBatch memory leak when the program threw an …
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/join/AbstractHashBinaryRecordBatch.java
Labels: bug, backport-to-stable
