Repository apache/drill, pull requests merged in 2024-07, with the labels that each got.

#2921 DRILL-8501: Json Conversion UDF Not Respecting System JSON Options
  exec/java-exec/src/main/java/org/apache/drill/exec/expr/fn/impl/conv/JsonConvertFrom.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/json/TestJsonConversionUDF.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/json/TestJsonNanInf.java
  exec/java-exec/src/test/resources/jsoninput/allTypes.csvh
Labels: bug, code-cleanup, doc-impacting, minor-update, backport-to-stable

#2925 [MINOR UPDATE] update to poi 5.3.0
  contrib/format-excel/pom.xml
  pom.xml
Labels: minor-update, dependencies, backport-to-stable

#2923 DRILL-8502: some boot options with drill.exec.options prefix are missed in configuration options
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/resources/drill-module.conf
Labels: code-cleanup, regression

#2926 Add threadSafe annotation to fmpp Maven Plugin
  tools/fmpp/src/main/java/org/apache/drill/fmpp/mojo/FMPPMojo.java
Labels: minor-update, backport-to-stable

#2927 DRILL-8503: Add Configuration Option to Skip Host Validation for Splunk
  contrib/storage-splunk/README.md
  contrib/storage-splunk/pom.xml
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkConnection.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkPluginConfig.java
  contrib/storage-splunk/src/main/java/org/apache/drill/exec/store/splunk/SplunkUtils.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkConnectionTest.java
  contrib/storage-splunk/src/test/java/org/apache/drill/exec/store/splunk/SplunkTestSuite.java
Labels: enhancement, doc-impacting, dependencies

#2907 DRILL-8492: Read Parquet Microsecond Columns as Bigint
  exec/java-exec/src/main/java/org/apache/drill/exec/ExecConstants.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetReaderConfig.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ColumnReaderFactory.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/columnreaders/ParquetToDrillTypeConverter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/metadata/FileMetadataCollector.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet2/DrillParquetGroupConverter.java
  exec/java-exec/src/main/resources/drill-module.conf
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/ParquetSimpleTestFileGenerator.java
  exec/java-exec/src/test/java/org/apache/drill/exec/store/parquet/TestMicrosecondColumns.java
  exec/java-exec/src/test/resources/parquet/microseconds.parquet
  exec/java-exec/src/test/resources/parquet/microseconds_small_diff.parquet
Labels: enhancement, doc-impacting
