Repository apache/drill, pull requests merged in 2025-07, with the labels that each got.

#3000 DRILL-8528: HBase Limit Push Down
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseGroupScan.java
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBasePushFilterIntoScan.java
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseRecordReader.java
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseScanBatchCreator.java
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseStoragePlugin.java
  contrib/storage-hbase/src/main/java/org/apache/drill/exec/store/hbase/HBaseSubScan.java
  contrib/storage-hbase/src/test/java/org/apache/drill/hbase/TestHBaseFilterPushDown.java
Labels: enhancement, performance

#3006 [MINOR UPDATE] Update Mongo Client
  pom.xml
Labels: code-cleanup, dependencies, backport-to-stable

#3003 [MINOR UPDATE] Bump Delta Lake to Version 4.0
  contrib/format-deltalake/pom.xml
Labels: minor-update, dependencies, backport-to-stable

#3010 [MINOR UPDATE] upgrade mysql connector due to CVE
  contrib/storage-jdbc/pom.xml
Labels: dependencies
