Repository apache/drill, pull requests merged in 2025-05, with the labels that each got.

#2987 DRILL-8523: Remove Support for Java 8
  .github/workflows/ci.yml
  exec/java-exec/src/main/java/org/apache/drill/exec/compile/ClassCompilerSelector.java
  exec/java-exec/src/main/java/org/apache/drill/exec/compile/ClassTransformer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/compile/QueryClassLoader.java
  exec/java-exec/src/test/java/org/apache/drill/PlanningBase.java
  exec/java-exec/src/test/java/org/apache/drill/exec/compile/TestClassTransformation.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/TestNestedDateTimeTimestamp.java
  exec/java-exec/src/test/java/org/apache/drill/exec/physical/impl/writer/TestParquetWriter.java
  exec/java-exec/src/test/java/org/apache/drill/exec/rpc/data/TestBitRpc.java
  exec/java-exec/src/test/java/org/apache/drill/exec/vector/accessor/GenericAccessorTest.java
  exec/java-exec/src/test/java/org/apache/drill/exec/work/fragment/FragmentStatusReporterTest.java
  exec/jdbc-all/pom.xml
  pom.xml
Labels: code-cleanup, security, dependencies, ci, backport-to-stable

#2988 DRILL-8524: Drill Adding Duplicate Parameters in Offset Paginator
  contrib/storage-http/pom.xml
  contrib/storage-http/src/main/java/org/apache/drill/exec/store/http/paginator/OffsetPaginator.java
Labels: bug, minor-update, backport-to-stable

#2986 DRILL-8521: Update Parquet due to CVE-2025-30065
  contrib/storage-hive/hive-exec-shade/pom.xml
  contrib/storage-kafka/pom.xml
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ColumnDataReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/ParquetRecordWriter.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet2/DrillParquetReader.java
  exec/java-exec/src/main/java/org/apache/parquet/hadoop/ColumnChunkIncReadStore.java
  exec/java-exec/src/main/java/org/apache/parquet/hadoop/ParquetColumnChunkPageWriteStore.java
  exec/java-exec/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java
  pom.xml
Labels: code-cleanup, security, dependencies, backport-to-stable

#2991 DRILL-8525: Migrate Fully to Apache Commons Collections 4.x
  contrib/storage-mongo/src/main/java/org/apache/drill/exec/store/mongo/MongoRecordReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/coord/zk/ZKClusterCoordinator.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/base/AbstractGroupScanWithMetadata.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/aggregate/HashAggBatch.java
  exec/java-exec/src/main/java/org/apache/drill/exec/physical/impl/project/ProjectionMaterializer.java
  exec/java-exec/src/main/java/org/apache/drill/exec/planner/physical/LateralJoinPrel.java
  exec/java-exec/src/main/java/org/apache/drill/exec/server/options/SystemOptionManager.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/dfs/easy/EasyGroupScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/ischema/RecordCollector.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet/AbstractParquetGroupScan.java
  exec/java-exec/src/main/java/org/apache/drill/exec/store/parquet2/DrillParquetReader.java
  exec/java-exec/src/main/java/org/apache/drill/exec/work/filter/RuntimeFilterRouter.java
  pom.xml
Labels: code-cleanup, dependencies
